<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/** @var \Magento\Tax\Block\Item\Price\Renderer $block */

$_item = $block->getItem();
/** @var \Magento\Sales\Model\Order $_order */
$_order = $_item->getOrder();
?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <?php if ($block->displayBothPrices()): ?>
        <span class="label"><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
    <?php endif; ?>
    <?= /* @noEscape */ $_order->formatPrice($_item->getRowTotal()) ?>
<?php endif; ?>


<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <?php if ($block->displayBothPrices()): ?>
        <br /><span class="label"><?= $escaper->escapeHtml(__('Incl. Tax')) ?>:</span>
    <?php endif; ?>
    <?php $_incl = $this->helper(\Magento\Checkout\Helper\Data::class)->getSubtotalInclTax($_item); ?>
    <?= /* @noEscape */ $_order->formatPrice($_incl) ?>
<?php endif; ?>
