<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Store\Block\Switcher $block */

$currencies = $block->getCurrencies();
$currentCurrencyCode = $block->getCurrentCurrencyCode();
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<div class="relative w-full lg:w-max min-h-[28px]" x-data="currencySwitcher('<?= $escaper->escapeHtml($currentCurrencyCode) ?> - <?= $currencies[$currentCurrencyCode] ? $escaper->escapeHtml($currencies[$currentCurrencyCode]) : '' ?>')">
    <button type="button" @click="isCurrencySwitcher = !isCurrencySwitcher" class="w-full relative cursor-pointer font-medium rounded pl-5 py-3 lg:text-sm lg:py-0 lg:pl-3 pr-10 text-left text-gray-900 lg:text-white sm:leading-6" :aria-haspopup="isCurrencySwitcher" :aria-expanded="isCurrencySwitcher" aria-labelledby="listbox-label">
        <span class="min-h-[20px] inline-block" x-text="selectedCurrency"></span>
        <?php if (!empty($currencies)) { ?>
            <span class="pointer-events-none absolute z-10 inset-y-0 right-0 ml-3 flex items-center pr-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-4 w-4 text-gray-900 lg:text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                </svg>
            </span>
        <?php } ?>
    </button>
    <?php if (!empty($currencies)) { ?>
        <ul x-cloak x-show="isCurrencySwitcher" x-transition:leave="transition ease-in duration-100" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" @click.away="isCurrencySwitcher = false" class="absolute z-[500] right-0 top-full w-full lg:w-max rounded p-2 bg-white origin-top-right rounded-md bg-white shadow-lg focus:outline-none ring-1 ring-black ring-opacity-5 focus:outline-none" tabindex="-1" role="listbox" aria-labelledby="listbox-label" aria-activedescendant="listbox-option-3">
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <?php $selectedCurrency = $_code; ?>
                    <li class="currency-<?= $escaper->escapeHtmlAttr($_code) ?> switcher-option">
                        <a href="javascript:void(0)" @click="changeCurrency('<?= $escaper->escapeUrl($block->getUrl('directory/currency/switch', ['currency' => $escaper->escapeJs($selectedCurrency)])) ?>')" id="currency" name="currency" class="text-gray-700 font-medium block p-2 rounded text-sm capitalize hover:bg-gray-100 focus:bg-primary focus:text-white"><?= $escaper->escapeHtml($_code) ?> - <?= $escaper->escapeHtml($_name) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php } ?>
</div>
<?php endif; ?>
