<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Review\Block\Product\View\ListView;

/**
 * @var ListView $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>
    <div class="block w-full">
        <?php if (!$block->getHideTitle()): ?>
            <h2 class="text-base font-semibold leading-7 text-gray-900"><?= $escaper->escapeHtml(__('Customer Reviews')) ?></h2>
        <?php endif ?>
        <div class="mt-6 space-y-10 divide-y divide-gray-200">
            <?php foreach ($_items as $_review): ?>
                <div class="pt-10 lg:grid lg:grid-cols-1 lg:gap-x-8">
                    <div class="block">
                        <?php if (count($_review->getRatingVotes())): ?>
                            <div class="flex flex-row gap-5 flex-wrap items-start mb-4">
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                    <div class="flex flex-col justify-start items-start">
                                        <span class="block text-sm font-medium leading-6 text-gray-900">
                                            <?= $escaper->escapeHtml($_vote->getRatingCode()) ?>
                                        </span>
                                        <svg class="hidden">
                                            <symbol id="star" width="32" height="30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M31.77 11.857H19.74L15.99.5l-3.782 11.357H0l9.885 6.903-3.692 11.21 9.736-7.05 9.796 6.962-3.722-11.18 9.766-6.845z" fill="currentColor" />
                                            </symbol>
                                        </svg>
                                        <div class="relative mt-2 inline-block">
                                            <div class="text-gray-200 inline-flex space-x-1">
                                                <svg viewBox="0 0 32 30" class="w-4 h-4">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                            </div>
                                            <div class="overflow-hidden absolute left-0 top-0 text-primary flex space-x-1" style="width:<?= $escaper->escapeHtml($_vote->getPercent()) ?>%">
                                                <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                                <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                                    <use xlink:href="#star"></use>
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <div class="mt-4 lg:mt-6 xl:mt-0">
                            <h3 class="font-medium text-gray-900"><?= $escaper->escapeHtml($_review->getTitle()) ?></h3>
                            <div class="mt-2 space-y-6 text-gray-800">
                                <?= /* @noEscape */ nl2br($escaper->escapeHtml($_review->getDetail())) ?>
                            </div>
                        </div>
                    </div>
                    <div class="block mt-6">
                        <p class="font-medium text-gray-900"><?= $escaper->escapeHtml($_review->getNickname()) ?></p>
                        <time datetime="2021-01-06"><?= $escaper->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?></time>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="toolbar review-toolbar flex flex-col sm:flex-row flex-wrap justify-end items-center md:items-start gap-5 mt-5 pt-5 border-t border-gray-200">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
<?php endif; ?>