<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/**
 * @var \Magento\Review\Block\Rating\Entity\Detailed $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if (!empty($collection) && $collection->getSize()): ?>
    <div class="table-wrapper">
        <table class="data table ratings review summary">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Ratings Review Summary')) ?></caption>
            <tbody>
            <?php foreach ($collection as $_rating): ?>
                <?php if ($_rating->getSummary()): ?>
                    <tr>
                        <th class="label" scope="row"><?= $escaper->escapeHtml(__($_rating->getRatingCode())) ?></th>
                        <td class="value">
                            <div class="rating box">
                                <div class="rating"></div>
                            </div>
                            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                "width:" . /* @noEscape */ ceil($_rating->getSummary()) . "%;",
                                'div.rating.box div.rating'
                            ) ?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
