<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label font-medium text-base">
        <span><?= $escaper->escapeHtml($_option->getTitle()) ?></span>
        <?php if ($_option->getRequired()): ?>
            <span class="text-required ml-1">*</span>
        <?php endif; ?>
    </label>
    <div class="control mt-2">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>" 
                   class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?> bundle option"/>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>][]"
                    data-selector="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>][]"
                    class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?> multiselect product bundle option change-container-classname rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6 product-bundle-option w-full focus:outline-none focus:ring-primary sm:w-max"
                    @change="changeBundleOption($event)"
                    <?php if ($_option->getRequired()) { echo 'data-validate={required:true}'; } ?>>
                <?php if (!$_option->getRequired()): ?>
                    <option value=""><?= $escaper->escapeHtml(__('None')) ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                            <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                        <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>
