<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()):
    $params = json_decode($block->getMoveFromCartParams(), true);
    $url = $params['action'];
    $itemId = $params['data']['item'];
    $uenc = $params['data']['uenc'];
    ?>
   <button type="button" onclick="itemMoveToWishlist('<?= $escaper->escapeHtml($itemId) ?>', '<?= $escaper->escapeHtml($uenc) ?>')" title="<?= $escaper->escapeHtml(__('Move to Wishlist')) ?>" class="use-ajax action towishlist action-towishlist group inline-block cursor-pointer p-2 rounded-full hover:bg-primary/5">
      <span class="sr-only"><?= $escaper->escapeHtml(__('Move to Wishlist')) ?></span>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-6 h-6 transition-all fill-transparent duration-200 ease-in-out group-hover:fill-primary group-hover:stroke-primary">
         <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"></path>
      </svg>
   </button>
   <script>
      function itemMoveToWishlist(itemId, uenc) {
         const formData = new FormData();
         formData.append('item', itemId);
         formData.append('uenc', uenc);
         formData.append('form_key', getFormKeyCookie());
         fetch("<?= $escaper->escapeHtml($url) ?>", {method: "POST",body: formData,credentials: "include"})
         .then((response) => {
            if (response.ok) {
               window.location.href = response.url;
            }
         }).catch((error) => { console.error("Fetch error:", error); });
      }
   </script>
<?php endif; ?>