<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php if ($block->isWishListAllowed()): ?>
    <?php
    $wishlistParams = json_decode($block->getAddToWishlistParams($block->getProduct()), true);
    if (isset($wishlistParams['data']) && !empty($wishlistParams['data'])) {
        $params['product'] = isset($wishlistParams['data']['product'])?$wishlistParams['data']['product']:null;
        $params['uenc'] = isset($wishlistParams['data']['uenc'])?$wishlistParams['data']['uenc']:null;
    }
    $url = isset($wishlistParams['action'])?$wishlistParams['action']:$block->getUrl('wishlist/index/add');
    $formId = base64_encode($params['product']."-product_view_wishlist_form");
    $formId = preg_replace("/[^a-zA-Z0-9]/", "", $formId);
    ?>
    <form id="<?= $escaper->escapeHtmlAttr($formId) ?>">
        <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($params['product'])?>"/>
        <input type="hidden" name="uenc" value="<?= $escaper->escapeHtmlAttr($params['uenc'])?>"/>
        <button type="button" x-on:click="wishlistFormHandler('<?= $escaper->escapeHtmlAttr('product_addtocart_form') ?>', '<?= $escaper->escapeUrl($url) ?>')" title="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>" class="group action towishlist p-2 h-10 w-10 rounded-full bg-slate-200 text-gray-700">
            <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
            <span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5" data-slot="icon" class="w-6 h-6 fill-none group-hover:fill-primary stroke-current group-hover:stroke-primary">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"></path>
                </svg>
            </span>
        </button>
    </form>
<?php endif; ?>
