<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>

<?php /** @var \Magento\Tax\Pricing\Render\Adjustment $block */ ?>
<?php if ($block->displayPriceIncludingTax()): ?>
    <?= /* @noEscape */ $block->getDisplayAmount() ?>
<?php elseif ($block->displayPriceExcludingTax()): ?>
    <?= /* @noEscape */ $block->getDisplayAmountExclTax() ?>
<?php elseif ($block->displayBothPrices()): ?>
    <?= /* @noEscape */ $block->getDisplayAmount() ?>
    <?php if ($block->getDisplayAmountExclTax() !== $block->getDisplayAmount()): ?>
        (+<?= /* @noEscape */ $block->getDisplayAmountExclTax() ?> <?= $escaper->escapeHtml(__('Excl. Tax')) ?>)
    <?php endif; ?>
<?php endif; ?>
