<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<div class="order-details-items shipments">
    <?= $block->getChildHtml('shipment_items') ?>
    <div class="actions-toolbar w-full shadow-sm border border-gray-100 rounded-lg mb-6 p-4 bg-white">
        <div class="secondary">
            <a href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>" class="action back primary-btn">
                <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
