<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = $block->getCouponCode() !== null && strlen($block->getCouponCode()) > 0;
?>


<div class="container mx-auto py-6 px-0">
    <div x-data="getProductDiscount()">
        <button x-on:click="discountCode=!discountCode" class="inline-flex justify-start items-center gap-x-1 text-md text-primary underline">
            <?= $escaper->escapeHtml(__('Apply Discount Code')) ?>
            <span class="transition-all rotate-0" :class="discountCode == true ? 'rotate-180' :'rotate-0'">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"></path>
                </svg>
            </span>
        </button>

        <div x-cloak x-show="discountCode" class="block py-5">
            <div class="block">
                <form id="discount-coupon-form" class="flex w-full justify-start items-start gap-x-2 gap-y-2 flex-col sm:flex-row">
                    <label for="discount" class="sr-only"><?= $escaper->escapeHtml(__('Apply Discount Code')) ?></label>
                    <div class="field">
                        <div class="mr-2">
                            <input id="coupon_code" name="coupon_code" type="text" <?= ($hasCouponCode) ? 'disabled' : '' ?> value="<?= $escaper->escapeHtmlAttr($block->getCouponCode()) ?>" placeholder="<?= $escaper->escapeHtmlAttr(__('Enter discount code')) ?>" autocomplete="discount" class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" />
                        </div>
                    </div>

                    <?php if (!$hasCouponCode): ?>
                        <button type="button" class="primary-btn" @click="applyCouponSubmit">
                            <span><?= $escaper->escapeHtml(__('Apply Discount')) ?></span>
                            <template x-if="isLoader">
                                <span role="status">
                                    <svg aria-hidden="true" class="w-5 h-5 ml-2 text-gray-400 animate-spin fill-white" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                                        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                                    </svg>
                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Loading...')) ?></span>
                                </span>
                            </template>
                        </button>

                    <?php else: ?>
                        <button type="button" value="<?= $escaper->escapeHtmlAttr(__('Cancel Coupon')) ?>" class="delete-btn" @click="applyCouponSubmit">
                            <span><?= $escaper->escapeHtml(__('Cancel Coupon')) ?></span>
                        </button>
                    <?php endif; ?>

                    <?php if (!$hasCouponCode): ?>
                        <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
                    <?php endif; ?>
                </form>
            </div>
            <span id="discount-message"></span>
        </div>
    </div>
</div>

<script>

    function getProductDiscount() {
        return {
            discountCode: false,
            isLoader: false,
            url: "<?= $escaper->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>",
            init() {
                const couponField = document.getElementById('coupon_code');
                if (couponField.value) {
                    this.discountCode = true;
                }
            },
            applyCouponSubmit() {
                this.isLoader = true;
                const formId = "discount-coupon-form";
                const form = document.getElementById(formId);
                if (!form) return;

                const inputFields = form.querySelectorAll('input[type="text"]');
                let isValid = true;

                inputFields.forEach(inputElement => {
                    if (!inputElement.value.trim()) {
                        const fieldContainer = inputElement.closest('.field');
                        this.displayValidationError(fieldContainer);
                        isValid = false;
                    } else {
                        const fieldContainer = inputElement.closest('.field');
                        this.removeValidationError(fieldContainer);
                    }
                });

                form.addEventListener("submit", function (event) { event.preventDefault(); });
                const formData = new FormData(form);
                formData.append('form_key', getFormKeyCookie());

                if (isValid) {
                    fetch(this.url, {
                        method: "POST",
                        body: formData,
                        credentials: "include"
                    })
                    .then((response) => {
                        if (response.ok) {
                            if (response.redirected) {
                                window.location.href = response.url;
                            } else {
                                getCookie("mage-messages");
                            }
                        } else {
                            console.error("Error:", response.status);
                            this.isLoader = false;
                        }
                    }).catch((error) => {
                        this.isLoader = false;
                        console.error("Fetch error:", error);
                    });
                }
            },

            displayValidationError(fieldContainer) {
                let errorMessageElement = fieldContainer.querySelector('.error-message');
                if (!errorMessageElement) {
                    const parentElement = document.createElement('div');
                    parentElement.setAttribute('class', 'vira-form-validation');
                    errorMessageElement = document.createElement('div');
                    errorMessageElement.classList.add('error-message');
                    errorMessageElement.textContent = 'Required field';
                    parentElement.appendChild(errorMessageElement);
                    fieldContainer.appendChild(parentElement);
                }
            },

            removeValidationError(fieldContainer) {
                const errorMessageElement = fieldContainer.querySelector('.error-message');
                if (errorMessageElement) {
                    errorMessageElement.remove();
                }
            }
        }
    }
</script>