<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <ul class="checkout methods items checkout-methods-items">
        <?php foreach ($methods as $method): ?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== ''): ?>
                <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
