<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div class="flex order-5" x-data="miniCart" @set-cart.window="cartData = $event.detail" @set-cartloader.window="isLoadingCart = $event.detail" x-id="['mini-cart-drawer']">
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <button type="button" role="button" title="Mini Cart" class="group flex items-center p-2 pr-0 relative" x-ref="slideTrigger" x-on:click="toggleSlideOver()" :aria-expanded="isMiniCartOpen" :aria-controls="$id('slide-over-button')">
            <svg class="h-7 w-7 flex-shrink-0 text-black lg:text-gray-700 hover:text-black" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
            </svg>
            <template x-if="cartData.summary_count > 0">
                <span class="inline-flex justify-center items-center absolute top-0 -right-2 w-[20px] h-[20px] text-xs leading-none text-center text-white uppercase transform rounded-full bg-primary">
                    <span x-show="!isLoadingCart" x-text="cartData.summary_count"></span>
                    <svg x-show="isLoadingCart" aria-hidden="true" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 text-white animate-spin fill-primary">
                        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                    </svg>
                </span>
            </template>
            <span class="sr-only"><?= $escaper->escapeHtml(__('items in cart, view bag')) ?></span>
        </button>
        <div class="relative z-50" aria-labelledby="slide-over-title" role="dialog" aria-modal="true" x-cloak x-ref="minicartDrawer" x-show="isMiniCartOpen" :id="$id('slider-over-button')" id="slider-over-button-1">
            <div class="fixed inset-0 bg-black/50 bg-opacity-75 transition-opacity" x-cloak x-show="isMiniCartOpen" x-transition:enter="ease-in-out duration-500" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in-out duration-500" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"></div>
            <div class="fixed inset-0 overflow-hidden" x-cloak x-show="isMiniCartOpen">
                <div class="absolute inset-0 overflow-hidden" x-cloak x-show="isMiniCartOpen">
                    <div class="pointer-events-none fixed inset-y-0 right-0 flex max-w-[80%]" x-cloak x-show='isMiniCartOpen'>
                        <div class="pointer-events-auto relative w-screen max-w-md" x-cloak x-show="isMiniCartOpen" x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" x-on:click.outside="close($refs.minicartDrawer)">
                            <div class="absolute -left-7 top-4 z-10" x-cloak x-show="isMiniCartOpen" x-transition:enter="ease-in-out duration-500" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in-out duration-500" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0">
                                <button type="button" role="button" title="close" class="relative rounded-md text-gray-300 hover:text-white" x-on:click="toggleSlideOver()">
                                    <span class="absolute -inset-2.5"></span>
                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Close panel')) ?></span>
                                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            </div>
                            <div class="flex h-full flex-col bg-white py-6 pb-0 shadow-xl">
                                <template x-if="cartData.summary_count">
                                    <div class="block" x-clock x-show="cartData.summary_count !== 0">
                                        <div class="px-4 sm:px-6">
                                            <h2 x-text="cartData.summary_count > 1 ? cartData.summary_count + ' Items in your Cart' : cartData.summary_count + ' Item in your Cart' " class="text-base font-semibold leading-6 text-gray-900"></h2>
                                        </div>
                                        <div class="relative mt-6 flex-1 flex flex-col justify-between items-start minicart-content-scrollable">
                                            <div class="w-full p-5 h-full minicart-lists">
                                                <ul role="list" class="-my-6 divide-y divide-gray-200">
                                                    <template x-if="cartData && cartData.items && Array.isArray(cartData.items)">
                                                        <template x-for="(product, index) in cartData?.items?.slice(0, totalNumberProductDisplay)" :key="product.item_id">
                                                            <li class="flex justify-between items-start py-6">
                                                                <div class="flex-shrink-0 overflow-hidden rounded-md border border-gray-200">
                                                                    <img :src="product.product_image.src" :alt="product.product_name" loading="eager" fetchpriority="high" :width="product.product_image.width" :height="product.product_image.height">
                                                                </div>
                                                                <div class="ml-4 flex flex-1 flex-col">
                                                                    <div>
                                                                        <div class="flex flex-col sm:flex-row gap-y-3 justify-between font-medium text-gray-900">
                                                                            <div class="mx-w-full break-words">
                                                                                <a :href="product.product_url" x-html="product.product_name"></a>
                                                                                <p class="text-xs text-gray-500" x-html="product.product_sku"></p>
                                                                            </div>
                                                                            <p class="ml-0 sm:ml-4" x-html="product.product_price"></p>
                                                                        </div>
                                                                    </div>
                                                                    <div class="space-y-2">
                                                                        <template x-if="product.product_type === 'configurable' || product.product_type === 'simple'">
                                                                            <template x-if="product.options[0]">
                                                                                <div x-data="{ showOptionsConfig: false }">
                                                                                    <button type="button" title="Show sptions" class="inline-flex justify-start items-center gap-x-1 text-sm text-primary underline" @click="showOptionsConfig= ! showOptionsConfig">
                                                                                        <?= $escaper->escapeHtml(__('Show options')) ?>
                                                                                        <span class="transition-all rotate-0" :class="showOptionsConfig == true ? 'rotate-180' :'rotate-0'">
                                                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                                                                                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"></path>
                                                                                            </svg>
                                                                                        </span>
                                                                                    </button>
                                                                                    <div x-cloak x-show="showOptionsConfig">
                                                                                        <template x-for="(option, optionIndex) in product.options" :key="optionIndex">
                                                                                            <div class="text-sm">
                                                                                                <p class="font-medium inline-block text-black" x-text="option.label + ':'"></p>
                                                                                                <p class="inline-block text-gray-500 font-medium" x-html="option.value"></p>
                                                                                            </div>
                                                                                        </template>
                                                                                    </div>
                                                                                </div>
                                                                            </template>
                                                                        </template>
                                                                        <template x-if="product.product_type === 'bundle'">
                                                                            <div x-data="{ showOptionsBundle: false }">
                                                                                <button type="button" title="Show sptions" class="inline-flex justify-start items-center gap-x-1 text-sm text-primary underline" @click="showOptionsBundle= ! showOptionsBundle">
                                                                                    <?= $escaper->escapeHtml(__('Show options')) ?>
                                                                                    <span class="transition-all rotate-0" :class="showOptionsBundle == true ? 'rotate-180' :'rotate-0'">
                                                                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                                                                            <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"></path>
                                                                                        </svg>
                                                                                    </span>
                                                                                </button>
                                                                                <div x-cloak x-show="showOptionsBundle" class="space-y-2">
                                                                                    <template x-for="(option, optionIndex) in product.options" :key="optionIndex">
                                                                                        <div class="text-sm">
                                                                                            <p class="font-medium inline-block text-black" x-text="option.label + ':'"></p>
                                                                                            <template x-for="(value, valueIndex) in option.value" :key="valueIndex">
                                                                                                <p class="inline-block text-gray-500 font-medium" x-html="value"></p>
                                                                                            </template>
                                                                                        </div>
                                                                                    </template>
                                                                                </div>
                                                                            </div>
                                                                        </template>
                                                                    </div>
                                                                    <div class="flex flex-col sm:flex-row gap-y-3 flex-1 mt-5 items-start sm:items-center justify-between text-sm">
                                                                        <div class="inline-block">
                                                                            <label for="mini-cart-qty" class="sr-only">
                                                                                <?= $escaper->escapeHtml(__('Qty')) ?>
                                                                            </label>
                                                                            <div class="quantity-wrapper flex justify-start items-center ring-1 ring-inset ring-gray-300 rounded-md">
                                                                                <button type="button" aria-label="Quantity Decrement" class="text-gray-800 w-9 h-9 flex justify-center items-center" x-on:click="handleDecrement(product)">
                                                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                                                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14" />
                                                                                    </svg>
                                                                                </button>
                                                                                <input type="number" name="mini-cart-qty" id="mini-cart-qty" min="0" x-model="product.qty" :value="product.qty" title="Qty" class="inline-block w-9 text-center p-0 h-9 ring-1 ring-inset ring-gray-300 border-0 text-gray-900 sm:text-sm focus:outline-none focus:ring-gray-300" x-on:change="handleQtyChange(product)" />

                                                                                <button type="button" aria-label="Quantity Increment" class="text-gray-800 w-9 h-9 flex justify-center items-center" x-on:click="handleIncrement(product)">
                                                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                                                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                                                                                    </svg>
                                                                                </button>
                                                                            </div>
                                                                        </div>
                                                                        <div class="flex justify-end items-center gap-x-3">
                                                                            <template x-if="product.product_type !== 'grouped'">
                                                                                <a :href="product.configure_url" class="cursor-pointer text-green-600" role="link" title="Edit">
                                                                                    <span>
                                                                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
                                                                                            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                                                                            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                                                                                        </svg>
                                                                                    </span>
                                                                                </a>
                                                                            </template>
                                                                            <button type="button" role="button" title="Remove" id="delete_product" x-on:click.prevent="handleProductRemove" x-bind:data-item-id="product.item_id" class="font-medium text-red-600 hover:text-red-500">
                                                                                <span>
                                                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                                                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                                                                    </svg>
                                                                                </span>
                                                                            </button>
                                                                        </div>
                                                                    </div>
                                                                     <template x-if="product.item_id === quantityChangeProduct && isQuantityError">
                                                                        <div class="error-message text-error mt-1 text-xs" x-text="isQuantityError"></div>
                                                                    </template>
                                                                </div>
                                                            </li>
                                                        </template>
                                                    </template>
                                                </ul>
                                            </div>
                                            <div class="bg-primary/5 p-5 w-full">
                                                <div class="flex justify-between text-base font-semibold text-gray-900">
                                                    <div><?= $escaper->escapeHtml(__('Subtotal')) ?></div>
                                                    <div x-html="cartData.subtotal"></div>
                                                </div>
                                                <p class="mt-0.5 text-xs text-gray-600">
                                                    <?= $escaper->escapeHtml(__('We calculate taxes and shipping at the time of checkout.')) ?></p>
                                                <div class="mt-6">
                                                    <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/')) ?>" class="primary-btn w-full px-6 py-3 text-base">
                                                        <?= $escaper->escapeHtml(__('Checkout')) ?>
                                                    </a>
                                                </div>
                                                <div class="mt-6 flex justify-center text-center text-sm text-gray-500">
                                                    <p>
                                                        or
                                                        <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/')) ?>" class="font-medium text-primary transition-all hover:text-primary/70">
                                                            <?= $escaper->escapeHtml(__('View and Edit Cart')) ?>
                                                            <span aria-hidden="true"> &rarr;</span>
                                                        </a>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </template>
                                <div x-clock x-show="cartData.length == 0 || cartData.summary_count == 0" class="flex flex-col h-full justify-center items-center p-5">
                                    <span>
                                        <svg class="h-16 w-16 flex-shrink-0 text-gray-700" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" aria-hidden="true">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"></path>
                                        </svg>
                                    </span>
                                    <h2 class="mt-3 text-lg font-semibold leading-6 text-gray-900">
                                        <?= $escaper->escapeHtml(__('Your cart is empty')) ?>
                                    </h2>
                                    <p class="text-gray-600 mt-2 text-sm text-center">
                                        <span class="block"><?= $escaper->escapeHtml(__('You have no items in your shopping cart.')) ?></span>
                                        <span class="block"><?= $escaper->escapeHtml(__("Let's go buy something!")) ?></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <a class="action showcart relative" href="<?= $escaper->escapeUrl($block->getShoppingCartUrl()) ?>">
            <span class="sr-only"><?= $escaper->escapeHtml(__('My Cart')) ?></span>
            <svg class="h-7 w-7 flex-shrink-0 text-black lg:text-gray-700 hover:text-black" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
            </svg>
            <template x-if="cartData.summary_count > 0">
                <span class="inline-flex justify-center items-center absolute top-0 -right-2 w-[20px] h-[20px] text-xs leading-none text-center text-white uppercase transform rounded-full bg-primary">
                    <span x-show="!isLoadingCart" x-text="cartData.summary_count"></span>
                    <svg x-show="isLoadingCart" aria-hidden="true" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 text-white animate-spin fill-primary">
                        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                    </svg>
                </span>
            </template>
        </a>
    <?php endif ?>
    <div class="relative z-50" role="dialog" aria-modal="true" x-cloak x-show="showConfirmation">
        <div class="fixed inset-0 bg-black/50 bg-opacity-25 transition-opacity" x-cloak x-show="showConfirmation" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"></div>
        <div class="fixed inset-0 z-10 w-screen overflow-y-auto p-4 sm:p-6 md:p-20" x-cloak x-show="showConfirmation" >
            <div class="mx-auto max-w-md transform divide-y divide-gray-100 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black ring-opacity-5 transition-all" x-cloak x-show="showConfirmation" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-95">
                <div class="relative">
                    <div class="p-5 space-y-5" x-bind:id="'mini-cart-item-remove-' + deleteItemInfo.id">
                        <div>
                            <p class="text-sm leading-6 m-0 mt-1 text-gray-800">
                                <?= $escaper->escapeHtml(__('Are you sure you would like to remove this item from the shopping cart?')) ?>
                            </p>
                        </div>
                    </div>

                    <div class="flex justify-end items-center gap-5 p-4">
                        <button type="button" @click="handleCancelItem" class="inline-block text-sm leading-6 font-medium">
                            <?= $escaper->escapeHtml(__('Cancel')) ?>
                        </button>
                        <button type="button" @click="itemDelete(deleteItemInfo)" class="inline-flex justify-center items-center gap-3 transition-all rounded-md bg-primary px-3 py-1.5 text-sm font-medium leading-6 text-white shadow-sm hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary">
                            <template x-if="deleteItemConfirm">
                                <span class="w-5 h-5 inline-block border-2 border-white border-r-transparent rounded-full animate-spin"></span>
                            </template>
                            <span><?= $escaper->escapeHtml(__('Remove')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="all-product-items-qty" class="hidden"></div>
<div id="all-load-data" class="hidden"></div>
