<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/**
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit);
$childHtml = $block->getChildHtml();
?>

<nav class="navigation" data-action="navigation">
    <ul class="justify-start items-start w-full lg:w-max lg:flex lg:ml-8 lg:flex-row h-full">
        <?= /* @noEscape */ $menuHtml ?>
        <?= /* @noEscape */ $childHtml ?>
    </ul>
</nav>
