<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Customer\Block\Widget\Dob $block */

$translatedCalendarConfigJson = $block->getTranslatedCalendarConfigJson();
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
$viewModel = $block->getView();
$dobDate = $block->getValue();
?>

<div class="col-span-12 sm:col-span-6 <?= $escaper->escapeHtmlAttr($fieldCssClass) ?>">
    <label for="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>" class="block text-sm font-medium leading-6 text-gray-900">
        <?= $escaper->escapeHtml(__('Date of Birth')) ?>
        <?php if ($block->isRequired()): ?>
            <span class="inline-block ml-[2px] text-required">*</span>
        <?php endif; ?>
    </label>
    <div class="mt-2">
        <?php $yesterday = date('Y-m-d', strtotime('-1 day')); ?>
        <input type="text" class="block w-full rounded-md border-0 py-2.5 text-gray-900 cursor-pointer ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6 datePicker" data-post="<?= $escaper->escapeHtmlAttr($translatedCalendarConfigJson, ENT_QUOTES, 'UTF-8') ?>" name="dob" <?= $block->isRequired() ? ' required' : '' ?> id="dob" value="<?= $escaper->escapeHtmlAttr($dobDate) ?>"/>
        <?php if ($_message = $block->getAdditionalDescription()): ?>
            <div class="note"><?= $escaper->escapeHtml($_message) ?></div>
        <?php endif; ?>
    </div>
</div>
