<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Customer\Block\Widget\Taxvat $block */
?>

<div class="taxvat<?= $escaper->escapeHtmlAttr($block->isRequired()) ? ' required' : ''; ?> col-span-12 sm:col-span-6">
    <label for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
    class="block text-sm font-medium leading-6 text-gray-900">
        <?= $escaper->escapeHtml(__('Tax/VAT Number')) ?>
        <?php if ($block->isRequired()): ?>
            <span class="inline-block ml-[2px] text-required">*</span>
        <?php endif; ?>
    </label>
    <div class="mt-2">
        <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
        value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>"
        title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>"
        x-on:input.debounce="onChange" <?php if ($block->isRequired()): ?>required<?php endif; ?>
        class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6 <?= $escaper->escapeHtmlAttr($block->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('taxvat')) ?>" />
    </div>
</div>
