<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>
<div class="telephone col-span-6 <?= $escaper->escapeHtmlAttr($block->isRequired()) ? 'required' : '' ?>">
    <label for="telephone" class="block text-sm leading-6 text-gray-900">
        <?= $escaper->escapeHtml(__('Phone Number')) ?>
        <?php if ($block->isRequired()): ?>
            <span class="text-required ml-1">*</span>
        <?php endif; ?>
    </label>
    <div class="mt-1">
        <input type="tel" name="telephone" id="telephone" x-on:input.debounce="onChange"
        <?php if ($block->isRequired()): ?>required<?php endif; ?> 
        value="<?= $escaper->escapeHtmlAttr($block->getTelephone()) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
        class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6 <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('telephone')) ?>">
    </div>
</div>