<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

 use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */

?>
<li>
    <a class="inline-block leading-6 p-[0.8em] lg:p-[0.2em] text-gray-700 hover:text-gray-800 hover:underline" href="<?= $escaper->escapeUrl($block->getHref()) ?>" title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>">
        <?= $escaper->escapeHtmlAttr($block->getLabel())?>
    </a>
</li>
