<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $block->getImage()->getUrl($_category)) {
    $_imgHtml = '
        <div class="category-image">
            <img src="'. $escaper->escapeUrl($_imgUrl). '" alt="'. $escaper->escapeHtmlAttr($_category->getName()). '" title="'. $escaper->escapeHtmlAttr($_category->getName()). '" class="image block" />
        </div>
        ';
    $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
    /* @noEscape */
    echo $_imgHtml;
}
?>
