<?php
/**
 * Copyright 2023 Adobe
 * All Rights Reserved.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Recent */
/** @var $viewModel \Magento\OrderCancellationUi\ViewModel\Config */
$viewModel = $block->getViewModel();
$_orders = $block->getOrders();
$count = count($_orders);
?>
<div class="block block-dashboard-orders w-full shadow-sm border border-gray-100 rounded-lg p-4 bg-white" x-data="myOrderView()">
    <div class="mb-5 pb-2 border-b border-gray-200 flex justify-between items-center gap-5">
        <div class="block-title order text-lg text-gray-800 font-semibold">
            <?= $escaper->escapeHtml(__('Recent Orders')) ?>
        </div>
        <?php if ($count > 0): ?>
            <a class="action view text-primary text-sm hover:underline" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block">
    <?= $block->getChildHtml() ?>
    <?php if ($count > 0): ?>
        <div class="block overflow-x-auto">
            <table class="min-w-full table border-collapse" id="my-orders-table">
                <tbody>
                    <tr class="border-b border-gray-200 hidden md:table-row">
                        <th scope="col" class="col id w-[115px] id">
                            <div class="p-2 text-left text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Order #')) ?>
                            </div>
                        </th>
                        <th scope="col" class="col id w-[115px] date">
                            <div class="p-2 text-left text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Date')) ?></th>
                            </div>
                        </th>
                        <th scope="col" class="col id w-[115px] shipping">
                            <div class="p-2 text-left text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Ship To')) ?>
                            </div>
                        </th>
                        <th scope="col" class="col id w-[115px] total">
                            <div class="p-2 text-center text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Order Total')) ?>
                            </div>
                        </th>
                        <th scope="col" class="col id w-[115px] status">
                            <div class="p-2 text-center text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Status')) ?>
                            </div>
                        </th>
                        <th scope="col" class="col id w-[115px] actions">
                            <div class="p-2 text-center text-md font-semibold text-gray-800">
                                <?= $block->escapeHtml(__('Action')) ?>
                            </div>
                        </th>
                    </tr>
                    <?php foreach ($_orders as $_order): ?>
                        <tr class="border-b border-gray-200 pb-4 mb-4 block md:table-row last:border-b-0">
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id p-2 py-3 text-md text-gray-900 align-middle before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:pl-2">
                                <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date p-2 py-3 text-md text-gray-900 align-middle before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:pl-2">
                                <?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping p-2 py-3 text-md text-gray-900 align-middle before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:pl-2">
                                <?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total text-left p-2 py-3 text-md text-gray-900 align-middle font-medium before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:text-center md:pl-2">
                                <?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status text-left p-2 py-3 text-md text-gray-900 align-middle before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:text-center md:pl-2">
                                <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions text-left p-2 py-3 text-md text-gray-900 align-middle before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative pl-[45%] md:text-center md:pl-2">
                                <div class="inline-flex items-center gap-4">
                                    <?php if ($_order->getStatus() != 'received'): ?>
                                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view inline-block p-2 rounded-full text-primary transition-all duration-200 ease-in-out hover:bg-primary/5">
                                            <span>
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"></path>
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                                </svg>
                                            </span>
                                        </a>
                                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)
                                            ->canReorder($_order->getEntityId())
                                        ): ?>
                                            <span class="text-gray-300">|</span>
                                            <a href="#" data-post='<?= /* @noEscape */
                                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                                ->getPostData($block->getReorderUrl($_order))
                                            ?>' class="action order inline-block">
                                                <span class="hover:underline"><?= $block->escapeHtml(__('Reorder')) ?></span>
                                            </a>
                                        <?php endif ?>
                                        <?php if ($viewModel->canCancel($_order->getEntityId())): ?>
                                            <span class="text-gray-300">|</span>
                                            <button type="button" data-increment-id="<?=/* @noEscape */ $_order->getIncrementId() ?>" class="cancel-order whitespace-nowrap inline-block" id="cancel-order-<?=/* @noEscape */ $_order->getId() ?>" x-on:click="openPopUpModal(<?= $block->escapeHtml($_order->getEntityId()) ?>)">
                                                <span class="hover:underline"><?= $block->escapeHtml(__('Cancel Order')) ?></span>
                                            </button>
                                            <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
                                                ->setOrder($_order)
                                                ->setReasons($viewModel->getCancellationReasons($_order->getEntityId()))
                                                ->setTemplate("Magento_OrderCancellationUi::cancel-order-modal.phtml")->toHtml()
                                            ?>
                                        <?php endif ?>
                                    <?php endif ?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
        </div>
    <?php endif; ?>
    </div>
</div>
<script>
    function myOrderView() {
        return {
            showConfirmation: false,
            url: '<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql',
            realOrderId: '',
            orderId: '',

            openPopUpModal(orderId) {
                this.orderId = orderId;
                this.showConfirmation = true;
                var button = document.getElementById('cancel-order-'+this.orderId);
                this.realOrderId = button.getAttribute('data-increment-id');
            },

            async handleCancelOrder(){
                const reasonSelect = document.getElementById('cancel-order-reason-'+ this.orderId);
                const selectedReason = reasonSelect.value;
                let mutation = `
                    mutation cancelOrder($order_id: ID!, $reason: String!) {
                      cancelOrder(input: {order_id: $order_id, reason: $reason}) {
                        error
                        order {
                          status
                        }
                      }
                    }`;
                const response = await fetch(this.url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        query: mutation,
                        variables: {
                            'order_id': this.orderId,
                            'reason': selectedReason
                        }
                    })
                });

                const responseData = await response.json();
                let type = 'success';
                let message;

                if (responseData.data.cancelOrder.error !== null) {
                    message = responseData.data.cancelOrder.error;
                    type = 'error';
                    this.showConfirmation = false;
                    let displayMessage = {
                        messages: [{
                            text: message,
                            type: type
                        }]
                    };

                    displayMessages(displayMessage.messages);
                } else {
                    message = responseData.data.cancelOrder.order.status;
                    let displayMessage = {
                        messages: [{
                            text: message,
                            type: type
                        }]
                    };
                    this.showConfirmation = false;

                    displayMessages(displayMessage.messages);
                    location.reload();
                }
            },
        }
    }
</script>
