<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php $_order = $block->getOrder() ?>

<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
    <div class="w-full shadow-sm border border-gray-100 rounded-lg p-4 bg-white mb-6">
        <div class="order-title flex gap-2 flex-wrap items-center py-3 justify-between w-full border-b border-gray-100 mb-4">
            <strong><?= $escaper->escapeHtml(__('Refund #')) ?><?= $escaper->escapeHtml($_creditmemo->getIncrementId()) ?> </strong>
            <div class="actions-toolbar space-x-5">
                <a href="<?= $escaper->escapeUrl($block->getPrintCreditmemoUrl($_creditmemo)) ?>" class="action print text-primary hover:underline inline-flex" target="_blank" rel="noopener">
                    <span><?= $escaper->escapeHtml(__('Print Refund')) ?></span>
                </a>
                <a href="<?= $escaper->escapeUrl($block->getPrintAllCreditmemosUrl($_order)) ?>" class="action print text-primary pb-2 hover:underline" target="_blank" rel="noopener">
                    <span><?= $escaper->escapeHtml(__('Print All Refunds')) ?></span>
                </a>
            </div>
        </div>

        <div class="table-wrapper order-items-creditmemo">
            <table class="data table table-order-items creditmemo w-full" id="my-refund-table-<?= $escaper->escapeHtml((int) $_creditmemo->getId()) ?>">
                <caption class="table-caption hidden"><?= $escaper->escapeHtml(__('Items Refunded')) ?></caption>
                <thead class="border-b border-gray-200 hidden md:table-header-group">
                    <tr>
                        <th class="col name p-2 text-left font-semibold"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                        <th class="col sku p-2 font-semibold"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                        <th class="col price p-2 font-semibold"><?= $escaper->escapeHtml(__('Price')) ?></th>
                        <th class="col qty p-2 font-semibold"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                        <th class="col subtotal p-2 font-semibold"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                        <th class="col discount p-2 font-semibold"><?= $escaper->escapeHtml(__('Discount Amount')) ?></th>
                        <th class="col total p-2 font-semibold"><?= $escaper->escapeHtml(__('Row Total')) ?></th>
                    </tr>
                </thead>
                <?php $_items = $_creditmemo->getAllItems(); ?>
                <?php foreach ($_items as $_item): ?>
                    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                        <tbody>
                            <?= $block->getItemHtml($_item) ?>
                        </tbody>
                    <?php endif; ?>
                <?php endforeach; ?>
                <tfoot class="w-full block md:table-footer-group">
                    <?= $block->getTotalsHtml($_creditmemo) ?>
                </tfoot>
            </table>
        </div>
        <?= $block->getCommentsHtml($_creditmemo) ?>
    </div>
<?php endforeach; ?>