<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// @deprecated
?>
<?php if (count($block->getStores())>1): ?>
<div class="form-language">
    <label for="select-language"><?= $escaper->escapeHtml(__('Your Language:')) ?></label>
    <select id="select-language" title="<?= $escaper->escapeHtmlAttr(__('Your Language')) ?>" onchange="window.location.href=this.value" class="flags">
    <?php foreach ($block->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $block->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?= $escaper->escapeUrl($_lang->getCurrentUrl()) ?>" style="background-image:url('<?= $escaper->escapeUrl($block->getViewFileUrl('images/flags/flag_' . $_lang->getCode() . '.gif')) ?>');"<?= /* @noEscape */ $_selected ?>><?= $escaper->escapeHtml($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
