<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \ViraXpress\Cms\Block\Block $block */
$blockId = $block->getConfig('viraxpress_config/footer/extra_block_id');
if (!empty($blockId)) {
    echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId($blockId)->toHtml();
}
?>
