<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
    <div class="bundle-actions">
        <button id="bundle-slide" x-data x-transition x-on:click="document.getElementById('bundle-container-wrapper').classList.remove('h-0'); window.scrollTo({top: document.getElementById('bundle-container').offsetTop, behavior: 'smooth'});" class="action primary customize primary-btn" type="button">
            <span><?= $escaper->escapeHtml(__('Customize and Add to Cart')) ?></span>
        </button>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            if (document.querySelectorAll('.checkout-cart-configure').length > 0) {
                document.getElementById('bundle-container-wrapper').classList.remove('h-0');
                window.scrollTo({
                    top: document.getElementById('bundle-container').offsetTop,
                    behavior: 'smooth'
                });
            }
        }, 100);
    </script>
<?php endif; ?>