<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $productType = $_product->getTypeId(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-to-cart flex justify-start flex-wrap items-end gap-5">
        <?php if ($block->shouldRenderQuantity() && $productType != 'downloadable'): ?>
            <div class="inline-block quantity-field">
                <label for="product_quantity" class="block text-base font-semibold leading-6 text-gray-900">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </label>
                <div class="quantity-wrapper mt-2 flex justify-start items-center ring-1 ring-inset ring-gray-300 rounded-md bg-white" x-data="updateQty(<?= $block->getProductDefaultQty() * 1 ?>)" x-init="init()">
                    <button type="button" id="handleDecrementPDP" aria-label="Quantity Decrement" class="text-gray-800 w-11 h-11 flex justify-center items-center" x-on:click="handleDecrement">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14"></path>
                        </svg>
                    </button>
                    <input type="number" name="qty" id="qty" min="1" form="product_addtocart_form" :value="productQty" title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>" class="inline-block w-11 text-center p-0 h-11 ring-1 ring-inset ring-gray-300 border-0 text-gray-900 sm:text-sm focus:outline-none focus:ring-gray-300" data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>" x-on:change="validateQuantity(event)" onkeydown="preventFormSubmission(event)" />
                    <button type="button" id="handleIncrementPDP" aria-label="Quantity Increment" class="text-gray-800 w-11 h-11 flex justify-center items-center" x-on:click="handleIncrement">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"></path>
                        </svg>
                    </button>
                </div>
            </div>
        <?php endif; ?>
        <div class="block flex-1">
            <button type="button" x-on:click="cartAddFormHandler('product_addtocart_form', '<?= $escaper->escapeUrl($block->getSubmitUrl($_product)) ?>')" role="button" title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>" class="w-full primary-btn inline-flex justify-center items-center gap-x-2">
                <span class="inline-block relative">
                    <template x-if="addToCartLoader == '<?= $escaper->escapeHtmlAttr($_product->getId()) ?>'">
                        <span class="bg-primary absolute inline-flex justify-center items-center w-full left-0 top-0 z-10 h-full">
                           <span class="w-5 h-5 inline-block border-2 border-white border-r-transparent rounded-full animate-spin"></span>
                        </span>
                    </template>
                    <svg class="w-6 h-6 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"></path>
                    </svg>
                </span>
                <span class="sr-only sm:not-sr-only"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </div>
        <div class="w-full flex justify-start items-center gap-5 flex-wrap">
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
<?php endif; ?>
<script>
    function updateQty(qty) {
        return {
            productQty: qty,
            handleDecrement() {
                this.productQty = Math.max(1, this.productQty - 1);
            },
            handleIncrement() {
                this.productQty++;
            },
            validateQuantity(event) {
                this.productQty = event.target.value || 1;
                var selectedQtyField = document.getElementById(event.target.id);
                if (this.productQty < 1 || isNaN(this.productQty)) {
                    event.target.value = 1;
                    this.productQty = 1;
                } else if(this.productQty % 1 !== 0) {
                    event.target.value = Math.round(this.productQty);
                    this.productQty = Math.round(this.productQty);
                }
            }
        };
    }

    function preventFormSubmission(event) {
        if (event.key === "Enter") {
            event.preventDefault();
        }
    }
</script>