<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_product = $block->getProduct(); ?>
<div class="product-add-form space-y-4">
    <form data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr((int)$_product->getId()) ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <input type="hidden" name="item"  value="<?= $escaper->escapeHtmlAttr((int)$block->getRequest()->getParam('id')) ?>" />
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()): ?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else: ?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'): ?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'): ?>
            <?php if ($_product->getTypeId() == \Magento\Bundle\Model\Product\Type::TYPE_CODE): ?>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-5" x-data="initBundleOption">
                    <?= $block->getChildChildHtml('options_container') ?>
                    <?= $block->getChildHtml('bundle_summary') ?>
                </div>
            <?php else: ?>
                <div class="grid grid-cols-12 gap-5">
                    <?= $block->getChildChildHtml('options_container') ?>
                    <?= $block->getChildHtml('bundle_summary') ?>
                </div>
            <?php endif; ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>