<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-x-10 gap-y-5" x-data="productMain" x-init="init()" @set-gallery.window="images = $event.detail.images">
    <?= $block->getChildHtml('product-media'); ?>
    <?= $block->getChildHtml('product-main'); ?>
</div>
