<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php /** @var $block \Magento\Downloadable\Block\Sales\Order\Email\Items\Downloadable */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder() ?>
<tr>
    <td class="item-info has-extra">
        <p class="product-name"><?= $escaper->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $escaper->escapeHtml(__('SKU')) ?>: <?= $escaper->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
        <dl>
            <?php foreach ($block->getItemOptions() as $option): ?>
            <dt><strong><em><?= $escaper->escapeHtml($option['label']) ?></em></strong></dt>
            <dd><?= $escaper->escapeHtml($option['value']) ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php if ($links = $block->getLinks()->getPurchasedItems()): ?>
        <dl>
            <dt><strong><em><?= $escaper->escapeHtml($block->getLinksTitle()) ?></em></strong></dt>
            <?php foreach ($links as $link): ?>
                <dd>
                    <?= $escaper->escapeHtml($link->getLinkTitle()) ?>&nbsp;
                    (<a href="<?= $escaper->escapeUrl($block->getPurchasedLinkUrl($link)) ?>"><?= $escaper->escapeHtml(__('download')) ?></a>)
                </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float)$_item->getQty() * 1 ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
