<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */


use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\Locale\LocaleFormatter;
use Magento\Framework\View\Element\BlockInterface;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var LocaleFormatter $localeFormatter
 * @var Escaper $escaper
 * @var BlockInterface $block
 */
$baseUrl = $escaper->escapeUrl($block->getBaseUrl());
$storeCodeUrls = $block->getConfig('web/url/use_store');
if ($storeCodeUrls) {
    $parsedUrl = parse_url($baseUrl);
    $baseUrl = $parsedUrl['scheme'] . '://' . $parsedUrl['host'] . '/';
}

$scriptString = '
    var LOCALE = \'' . /* @noEscape */ $escaper->escapeJs($localeFormatter->getLocaleJs()) .'\';
    var SPLIDE_JS = \'' . /* @noEscape */ $escaper->escapeJs($block->getViewFileUrl('core-js/splide.min.js')) .'\';
    var BASE_URL = \'' . /* @noEscape */ $escaper->escapeJs($block->getBaseUrl()) .'\';
    var STORAGE_KEY = \'vira-mage-cache-storage\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $escaper->escapeJs($block->getViewFileUrl('/')) . '\'
    };';

$styleString = '
    <style type="text/css">
        .background-image-66c42eb86db9a {
            background-image: url(' . $baseUrl .'media/wysiwyg/main_banner_VX_1.webp);
        }
        @media only screen and (max-width: 768px) and (min-width: 640px) {
            .background-image-66c42eb86db9a {
                background-image: url(' . $baseUrl .'media/wysiwyg/main_banner_VX-mobile.webp);
            }
        }
        @media only screen and (max-width: 640px) {
            .background-image-66c42eb86db9a {
                background-image: url(' . $baseUrl .'media/wysiwyg/main_banner_VX-mobile.webp);
            }
        }
    </style>';
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>


<?php
$themePath = $block->checkThemePath();

// Construct media URL
$baseUrl = $escaper->escapeUrl($block->getBaseUrl());
$storeCodeUrls = $block->getConfig('web/url/use_store');
if ($storeCodeUrls) {
    $parsedUrl = parse_url($baseUrl);
    $baseUrl = $parsedUrl['scheme'] . '://' . $parsedUrl['host'] . '/';
}
$customPath = 'vx/'.$themePath.'/web/';
$mediaUrl = $baseUrl . $escaper->escapeUrl($customPath);

// Define assets
$stylesheets = [
    'css/styles.css'
];


$staticAssets = [
    $baseUrl.'media/wysiwyg/main_banner_VX_1.webp',
    $baseUrl.'media/wysiwyg/main_banner_VX-mobile.webp'
];

// $fonts = [
//     'Inter-Regular.woff',
//     'Inter-Medium.woff',
//     'Inter-SemiBold.woff',
//     'Inter-Bold.woff'
// ];
?>

<?php  foreach ($staticAssets as $source): ?>
    <?= /* @noEscape */  $secureRenderer->renderTag(
        'link',
        [
            'rel' => 'preload',
            'fetchpriority' => 'high',
            'as' => 'image',
            'href' => $escaper->escapeUrl($source)
        ]
    ); ?>
<?php endforeach;?>

<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styleString, false); ?>
    
<?php /* foreach ($fonts as $font): ?>
    <?=  @noEscape   $secureRenderer->renderTag(
        'link',
        [
            'as' => 'font',
            'rel' => 'preload',
            'as' => 'font',
            'crossorigin' => 'anonymous',
            'type' => 'font/woff',
            'href' => $escaper->escapeUrl($mediaUrl . 'fonts/inter/woff/' . $escaper->escapeHtmlAttr($font))
        ]
    ); ?>
<?php endforeach; */ ?>


<?php foreach ($stylesheets as $stylesheet): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'link',
        [
            'rel' => 'stylesheet preload',
            'type' => 'text/css',
            'media' => 'all',
            'as' => 'style',
            'href' => $escaper->escapeUrl($mediaUrl . $escaper->escapeHtmlAttr($stylesheet) . '?' . time())
        ]
    ); ?>
<?php endforeach; ?>
