<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
/**
 * @var \Magento\Bundle\Block\Sales\Order\Items\Renderer $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 * @var \Magento\Bundle\ViewModel\Sales\Order\Items\Renderer $viewModel
 */
$parentItem = $block->getItem();
$viewModel = $block->getViewModel();
$items = $viewModel->getOrderItems((int)$parentItem->getOrderId(), (int)$parentItem->getId());
$index = 0;
$prevOptionId = '';
?>

<?php foreach ($items as $item): ?>

    <?php if ($block->getItemOptions()
        || $parentItem->getDescription()
        || $this->helper(Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order_item', $parentItem)
        && $parentItem->getGiftMessageId()): ?>
        <?php $showLastRow = true; ?>
    <?php else: ?>
        <?php $showLastRow = false; ?>
    <?php endif; ?>

    <?php if ($item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($item) ?>

        <?php if (isset($attributes['option_id']) && $prevOptionId != $attributes['option_id']): ?>
            <tr class="options-label block md:table-row">
                <td class="col label p-2 text-sm before:absolute before:left-0 before:font-semibold before:content-[attr(data-th)] md:before:content-none block md:table-cell relative font-semibold" colspan="5"><span><?= $escaper->escapeHtml($attributes['option_label']); ?></span></td>
            </tr>
            <?php $prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
<tr id="order-item-row-<?= /* @noEscape */ $item->getId() ?>"
    class="<?php if ($item->getParentItem()): ?> item-options-container pb-4 mb-4 block md:table-row last:border-b last:border-gray-200
    <?php else: ?>
        item-parent
    <?php endif; ?>"
    <?php if ($item->getParentItem()): ?>
        data-th="<?= $escaper->escapeHtmlAttr($attributes['option_label'] ?? ''); ?>"
    <?php endif; ?>>
    <?php if (!$item->getParentItem()): ?>
        <td class="col name text-left p-2 py-3 font-semibold before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell relative" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')); ?>">
            <div class="col-name-wrapper">
                <span class="product name product-item-name"><?= $escaper->escapeHtml($item->getName()); ?></span>
            </div>
        </td>
    <?php else: ?>
        <td class="col value text-left p-2 py-3 text-sm before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell <?= $item->getParentItem() ? 'before:text-sm' : 'before:text-base' ?>" data-th="<?= $escaper->escapeHtmlAttr(__('Product Name')); ?>">
            <div class="col-value-wrapper">
                <?= $block->getValueHtml($item); ?>
            </div>
        </td>
    <?php endif; ?>
    <td class="col sku text-left p-2 py-3 text-sm before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell relative <?= $item->getParentItem() ? 'before:text-sm' : 'before:text-base' ?>" data-th="<?= $escaper->escapeHtmlAttr(__('SKU')); ?>">
        <div class="col-sku-wrapper">
            <?= /* @noEscape */ $block->prepareSku($item->getSku()); ?>
        </div>
    </td>
    <td class="col price text-left p-2 py-3 font-semibold before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell relative <?= $item->getParentItem() ? 'before:text-sm' : 'before:text-base' ?>" data-th="<?= $escaper->escapeHtmlAttr(__('Price')); ?>">
        <div class="col-price-wrapper">    
            <?php if (!$item->getParentItem()): ?>
                <?= $block->getItemPriceHtml(); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </div>
    </td>
    <td class="col qty text-left p-2 py-3 text-sm before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell relative <?= $item->getParentItem() ? 'before:text-sm' : 'before:text-base' ?>" data-th="<?= $escaper->escapeHtmlAttr(__('Quantity')); ?>">
        <div class="col-qty-wrapper">
            <?php if (($item->getParentItem() && $block->isChildCalculated()) ||
            (!$item->getParentItem() && !$block->isChildCalculated()) ||
            ($item->getQtyShipped() > 0 && $item->getParentItem() && $block->isShipmentSeparately())): ?>
                <ul class="items-qty">
            <?php endif; ?>
            <?php if (($item->getParentItem() && $block->isChildCalculated()) ||
                (!$item->getParentItem() && !$block->isChildCalculated())): ?>
                <?php if ($item->getQtyOrdered() > 0): ?>
                    <li class="item">
                        <span class="title"><?= $escaper->escapeHtml(__('Ordered')); ?></span>
                        <span class="content">
                            <?= /* @noEscape */ $localeFormatter->formatNumber($item->getQtyOrdered() * 1); ?>
                        </span>
                    </li>
                <?php endif; ?>
                <?php if ($item->getQtyShipped() > 0 && !$block->isShipmentSeparately()): ?>
                    <li class="item">
                        <span class="title"><?= $escaper->escapeHtml(__('Shipped')); ?></span>
                        <span class="content">
                            <?= /* @noEscape */ $localeFormatter->formatNumber($item->getQtyShipped() * 1); ?>
                        </span>
                    </li>
                <?php endif; ?>
                <?php if ($item->getQtyCanceled() > 0): ?>
                    <li class="item">
                        <span class="title"><?= $escaper->escapeHtml(__('Canceled')); ?></span>
                        <span class="content">
                            <?= /* @noEscape */ $localeFormatter->formatNumber($item->getQtyCanceled() * 1); ?>
                        </span>
                    </li>
                <?php endif; ?>
                <?php if ($item->getQtyRefunded() > 0): ?>
                    <li class="item">
                        <span class="title"><?= $escaper->escapeHtml(__('Refunded')); ?></span>
                        <span class="content">
                            <?= /* @noEscape */ $localeFormatter->formatNumber($item->getQtyRefunded() * 1); ?>
                        </span>
                    </li>
                <?php endif; ?>
            <?php elseif ($item->getQtyShipped() > 0 && $item->getParentItem() && $block->isShipmentSeparately()): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')); ?></span>
                    <span class="content">
                        <?= /* @noEscape */ $localeFormatter->formatNumber($item->getQtyShipped() * 1); ?>
                    </span>
                </li>
            <?php else: ?>
                <span class="content">
                    <?= /* @noEscape */ $localeFormatter->formatNumber($parentItem->getQtyOrdered() * 1); ?>
                </span>
            <?php endif; ?>
            <?php if (($item->getParentItem() && $block->isChildCalculated()) ||
            (!$item->getParentItem() && !$block->isChildCalculated()) ||
            ($item->getQtyShipped() > 0 && $item->getParentItem() && $block->isShipmentSeparately())):?>
                </ul>
            <?php endif; ?>
        </div>
    </td>
    <td class="col subtotal text-left p-2 py-3 font-semibold before:font-semibold before:content-[attr(data-th)] md:before:content-none grid grid-cols-2 gap-x-2 md:table-cell relative <?= $item->getParentItem() ? 'before:text-sm' : 'before:text-base' ?>" data-th="<?= $escaper->escapeHtmlAttr(__('Subtotal')) ?>">
        <div class="col-subtotal-wrapper">    
            <?php if (!$item->getParentItem()): ?>
                <?= /* @noEscape */ $block->getItemRowTotalHtml(); ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </div>
    </td>
</tr>
<?php endforeach; ?>

<?php if ($showLastRow && (($options = $block->getItemOptions()) || $escaper->escapeHtml($item->getDescription()))): ?>
<tr>
    <td class="col options" colspan="5">
        <?php if ($options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($options as $option): ?>
                    <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $formattedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd><?php if (isset($formattedOptionValue['full_view'])): ?>
                            class="tooltip wrapper"
                        <?php endif; ?>>
                            <?= /* @noEscape */ $formattedOptionValue['value'] ?>
                            <?php if (isset($formattedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $escaper->escapeHtml($option['label']); ?></dt>
                                        <dd><?= /* @noEscape */ $formattedOptionValue['full_view']; ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd><?= $escaper->escapeHtml((isset($option['print_value']) ?
                                $option['print_value'] :
                                $option['value'])); ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?= $escaper->escapeHtml($item->getDescription()); ?>
    </td>
</tr>
<?php endif; ?>
