<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

use Magento\Vault\Block\Customer\CreditCards;
use Magento\Framework\Escaper;

/** @var CreditCards $block */
/** @var Escaper $escaper */
/* $escaper = $block->getEscaper(); */
$tokens = $block->getPaymentTokens();
?>
<?php if (count($tokens) !== 0): ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Stored Payment Methods')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col card-number">
                        <?= $escaper->escapeHtml(__('Card Number')) ?>
                    </th>
                    <th scope="col" class="col expire">
                        <?= $escaper->escapeHtml(__('Expiration Date')) ?>
                    </th>
                    <th scope="col" class="col card-type">
                        <?= $escaper->escapeHtml(__('Type')) ?>
                    </th>
                    <th scope="col" class="col actions">
                        &nbsp;
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($tokens as $token): ?>
                <?= $block->renderTokenHtml($token) ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php elseif (!$block->isExistsCustomerTokens()): ?>
    <div class="w-full shadow-sm border border-gray-100 rounded-lg p-4 bg-white mb-6 min-h-[140px] flex justify-center items-center">
        <div class="message info empty text-center flex flex-col text-gray-500 justify-start items-center gap-3">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="0.8" stroke="currentColor" class="w-14 h-14 text-gray-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Z" />
            </svg>
            <span>
                <?= $escaper->escapeHtml(__('You have no stored payment methods.')) ?>
            </span>
        </div>
    </div>
<?php endif; ?>