<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <div class="mt-6">
        <a href="<?= $escaper->escapeUrl($block->getCheckoutUrl()) ?>" data-role="proceed-to-checkout" class="primary-btn w-full px-6 py-3 text-base" title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>" <?php if ($block->isDisabled()): ?> disabled="disabled" <?php endif; ?>>
            <span class="text-center"><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
        </a>
    </div>
<?php endif?>
