<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
/**
 * @var \Magento\Review\Block\Customer\Recent $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
<div class="block block-reviews-dashboard w-full shadow-sm border border-gray-100 rounded-lg p-4 bg-white mb-6">
    <div class="block-title mb-5 pb-2 border-b border-gray-100 flex justify-between items-center gap-5">
        <strong class="block-title order text-lg text-gray-800 font-semibold"><?= $escaper->escapeHtml(__('My Recent Reviews')) ?></strong>
        <a class="action view text-primary text-sm hover:underline" href="<?= $escaper->escapeUrl($block->getAllReviewsUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('View All')) ?></span>
        </a>
    </div>
    <div class="block-content">
        <ol class="items divide-y divide-gray-200">
        <?php foreach ($block->getReviews() as $_review): ?>
            <li class="item py-2 first:pt-0 last:pb-0">
                <strong class="product-name">
                    <a href="<?= $escaper->escapeUrl($block->getReviewUrl($_review->getReviewId())) ?>">
                        <?= $escaper->escapeHtml($_review->getName()) ?>
                    </a>
                </strong>
                <?php if ($_review->getSum()): ?>
                    <?php $rating = $_review->getSum() / $_review->getCount() ?>
                    <div class="rating-summary flex gap-3 items-center py-1">
                         <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
                         <div class="rating-result" title="<?= $escaper->escapeHtmlAttr($rating) ?>%">
                             <div class="rating-summary stars relative top-[3px]">
                                <svg class="hidden">
                                    <symbol id="star" width="32" height="30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M31.77 11.857H19.74L15.99.5l-3.782 11.357H0l9.885 6.903-3.692 11.21 9.736-7.05 9.796 6.962-3.722-11.18 9.766-6.845z" fill="currentColor" />
                                    </symbol>
                                </svg>
                                <div class="relative inline-block leading-[normal]">
                                    <div class="text-gray-200 inline-flex space-x-1">
                                        <svg viewBox="0 0 32 30" class="w-4 h-4">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                    </div>
                                    <div class="overflow-hidden absolute left-0 top-0 text-primary flex space-x-1" style="width:<?= $escaper->escapeHtmlAttr($rating) ?>%">
                                        <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                        <svg viewBox="0 0 32 30" class="w-4 h-4 flex-shrink-0">
                                            <use xlink:href="#star"></use>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                         </div>
                        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                            "width:". $escaper->escapeHtmlAttr($rating) . "%",
                            'div.rating-result>span.rating_' . $escaper->escapeUrl($_review->getReviewId())
                        ) ?>
                     </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
