<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block \Magento\Catalog\Block\Product\View\Addto\Compare */
?>

<?php
$viewModel = $block->getData('addToCompareViewModel');
?>
<?php if ($viewModel->isAvailableForCompare($block->getProduct())): ?>
        <button type="button" class="group p-2 h-10 w-10 rounded-full bg-slate-200 text-gray-700" title="<?= $escaper->escapeHtml(__('Add to Compare')) ?>" role="button" @click.prevent="addToCompare(<?= (int)$block->getProduct()->getId() ?>)">
                <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                <span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-6 h-6 fill-none stroke-current group-hover:stroke-primary">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"></path>
                        </svg>
                </span>
        </button>
<?php endif; ?>