<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach; ?>
<div class="box-tocart flex justify-between items-end flex-wrap gap-4 space-y-4">
    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
        <div class="inline-block quantity-field">
            <label for="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" class="block text-sm font-medium leading-6 text-gray-900">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </label>
            <div class="mt-2 inline-flex justify-start items-center ring-1 ring-inset ring-gray-300 rounded-md">
                <button type="button" aria-label="Quantity Decrement" x-on:click="handleWishlistQtyDecrement('qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]')" class="text-gray-800 w-9 h-9 flex justify-center items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14"></path>
                    </svg>
                </button>

                <input type="tel" x-on:change="itemQtyValidate(event)" id="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" oninput="this.value = this.value.replace(/\D+/g, '')" class="inline-block w-9 text-center p-0 h-9 ring-1 ring-inset ring-gray-300 border-0 text-gray-900 sm:text-sm focus:outline-none focus:ring-gray-300" name="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */ $block->getAddToCartQty($item) * 1 ?>" <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>

                <button type="button" aria-label="Quantity Increment" x-on:click="handleWishlistQtyIncrement('qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]')" class="text-gray-800 w-9 h-9 flex justify-center items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"></path>
                    </svg>
                </button>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
        <div class="product-item-actions my-3">
            <button type="button" x-on:click='itemAddToCart(<?= $escaper->escapeHtmlAttr($block->getItemAddToCartParams($item)) ?> , event)' title="<?= $escaper->escapeHtmlAttr(__('Move to Cart')) ?>" class="flex relative py-2">
                <svg class="h-6 w-6 text-primary" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"></path>
                </svg>
                <span class="sr-only"><?= $escaper->escapeHtml(__('Move to Cart')) ?></span>
                <template x-if="addToCartLoader == '<?= $escaper->escapeHtmlAttr($item->getId()) ?>'">
                    <span class="bg-white absolute inline-flex justify-center items-center w-full left-0 top-0 z-10 h-full">
                        <svg aria-hidden="true" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-200 animate-spin fill-primary">
                            <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                            <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                        </svg>
                    </span>
                </template>
            </button>
        </div>
    <?php else: ?>
        <div class="block w-full">
            <?php if ($product->getIsSalable()): ?>
                <p class="available stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else: ?>
                <p class="unavailable stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>