<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="button" x-on:click='shareWishList(event)' name="save_and_share" title="<?= $escaper->escapeHtmlAttr(__('Share Wish List')) ?>" class="action share w-full sm:w-auto secondary-btn">
        <span><?= $escaper->escapeHtml(__('Share Wish List')) ?></span>
    </button>
<?php endif;?>
