<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

 use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
 use Magento\Framework\App\ActionInterface;
 
 /* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
 
 /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
 
 <?php
    $ratingModel = $block->getData("ratings_model");
    $configHelper = $block->getLayout()->createBlock(\ViraXpress\Catalog\Block\Product\ConfigBlock::class);
    $imagehelper = $configHelper->getImageHelper();
    $imageConfig = $configHelper->getConfig('viraxpress_config/image_resize/product_related_cross_up_image_resize');
    switch ($type = $block->getType()) {
        case 'related-rule':
            if ($exist = $block->hasItems()) {
                $type = 'related';
                $class = $type;
                $image = 'related_products_list';
                $title = __('Related Products');
                $items = $block->getAllItems();
                $limit = $block->getPositionLimit();
                $shuffle = (int) $block->isShuffled();
                $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
                $canItemsAddToCart = $block->canItemsAddToCart();

                $showAddTo = true;
                $showCart = false;
                $templateType = null;
                $description = false;
            }
            break;
        case 'related':
            /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
            if ($exist = $block->getItems()->getSize()) {
                $type = 'related';
                $class = $type;
                $image = 'related_products_list';
                $title = __('Related Products');
                $items = $block->getItems();
                $limit = 0;
                $shuffle = 0;
                $isWeightedRandom = 0;
                $canItemsAddToCart = $block->canItemsAddToCart();
                $showAddTo = true;
                $showCart = false;
                $templateType = null;
                $description = false;
            }
            break;
        case 'upsell-rule':
            if ($exist = $block->hasItems()) {
                $type = 'upsell';
                $class = $type;
                $image = 'upsell_products_list';
                $title = __('We found other products you might like!');
                $items = $block->getAllItems();
                $limit = $block->getPositionLimit();
                $shuffle = (int) $block->isShuffled();
                $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
                $showAddTo = false;
                $showCart = false;
                $templateType = null;
                $description = false;
                $canItemsAddToCart = false;
            }
            break;
        case 'upsell':
            /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
            if ($exist = count($block->getItemCollection()->getItems())) {
                $type = 'upsell';
                $class = $type;
                $image = 'upsell_products_list';
                $title = __('We found other products you might like!');
                $items = $block->getItemCollection()->getItems();
                $limit = $block->getItemLimit('upsell');
                $shuffle = 0;
                $isWeightedRandom = 0;
                $showAddTo = false;
                $showCart = false;
                $templateType = null;
                $description = false;
                $canItemsAddToCart = false;
            }
            break;
        case 'crosssell-rule':
            /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
            if ($exist = $block->hasItems()) {
                $type = 'crosssell';
                $class = $type;
                $image = 'cart_cross_sell_products';
                $title = __('More Choices:');
                $items = $block->getItemCollection();
                $showAddTo = true;
                $showCart = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                $description = false;
                $canItemsAddToCart = false;
            }
            break;
        case 'crosssell':
            /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
            if ($exist = count($block->getItems())) {
                $type = 'crosssell';
                $class = $type;
                $image = 'cart_cross_sell_products';
                $title = __('More Choices:');
                $items = $block->getItems();
                $showAddTo = true;
                $showCart = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                $description = false;
                $canItemsAddToCart = false;
            }
            break;
        case 'new':
            if ($exist = $block->getProductCollection()) {
                $type = 'new';
                $mode = 'grid';
                $type = $type . ' ' . $mode;
                $class = 'widget' . ' ' . $type;
                $image = 'new_products_content_widget_grid';
                $title = __('New Products');
                $items = $exist;
                $showAddTo = true;
                $showCart = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                $description = ($mode == 'list') ? true : false;
                $canItemsAddToCart = false;
            }
            break;
        default:
            $exist = null;
    }
    $_item = null;
    $blockObj = $block->getLayout()->createBlock(\Magento\Catalog\Block\Product\ListProduct::class);
    ?>
    <?php if ($exist): ?>
        <div class="bg-white col-span-12">
            <h2 id="related-heading" class="text-xl font-semibold text-gray-900 mb-6">
                <?= $escaper->escapeHtml($title) ?>
            </h2>
        </div>
        <div class="block w-full mb-10">
        <?php if (count($items) > 5) { ?>
            <div class="splide products-slider">
                <div class="splide__track">
                    <div class="splide__list">
                    <?php } else { ?>
                        <div class="grid grid-cols-12 gap-5">
                        <?php } ?>
                        <?php foreach ($items as $key => $_item): ?>
                            <?php $ratings = $ratingModel->getRatingSummary($_item) ?>
                            <?php if (!$ratings) { $ratings = 0; } ?>
                            <?php if (count($items) > 5) { ?>
                                <div class="splide__slide">
                                <?php } else { ?>
                                    <div class="col-span-12 md:col-span-6 lg:col-span-4 xl:col-span-3 relative group">
                                    <?php } ?>
                                    <div class="bg-white w-full border-2 border-transparent transition duration-500 hover:rounded hover:border-2 hover:border-[#F2F2F2] relative group">
                                        <?php $productImage = $block->getImage($_item, $image);
                                        $imageWidth = ($imageConfig['width']) ? $imageConfig['width'] : $productImage->getWidth();
                                        $imageHeight = ($imageConfig['height']) ? $imageConfig['height'] : $productImage->getHeight();
                                        $productImageConfig = $imagehelper->init($_item, $image)->resize($imageWidth, $imageHeight);
                                        $productImageUrl = $productImageConfig->getUrl(); ?>
                                        <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="flex justify-center overflow-hidden relative items-center">
                                            <img fetchpriority="high" loading="eager" data-src="<?= $escaper->escapeUrl($productImageUrl) ?>" alt="Product image" class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?> lazy transition duration-1000 ease-in-out group-hover:scale-[1.04]" width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>" height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>" alt="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>" title="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>" id="recommened-product-image-container-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                                            <span class="product photo skeleton skeleton-box absolute text-gray-400 bg-gray-100 inset-0 w-full h-full z-10 flex justify-center items-center">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12">
                                                  <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
                                                </svg>
                                            </span>
                                        </a>
                                        <div class="inline-flex absolute transition-all duration-500 ease-in-out top-4 right-4 flex-col gap-2 z-10">
                                            <?php
                                            $wishlistParams = json_decode($block->getAddToWishlistParams($_item), true);
                                            if (isset($wishlistParams['data']) && !empty($wishlistParams['data'])) {
                                                $params['product'] = isset($wishlistParams['data']['product']) ? $wishlistParams['data']['product'] : null;
                                                $params['uenc'] = isset($wishlistParams['data']['uenc']) ? $wishlistParams['data']['uenc'] : null;
                                            }
                                            $url = isset($wishlistParams['action']) ? $wishlistParams['action'] : $block->getUrl('wishlist/index/add');
                                            $wishlistFormId = base64_encode($params['product'] . "-product_list_wishlist_form");
                                            $wishlistFormId = preg_replace("/[^a-zA-Z0-9]/", "", $wishlistFormId);
                                            ?>
                                            <form id="<?= $escaper->escapeHtmlAttr($wishlistFormId) ?>">
                                                <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($params['product']) ?>" />
                                                <input type="hidden" name="uenc" value="<?= $escaper->escapeHtmlAttr($params['uenc']) ?>" />
                                                <button type="button" x-on:click="wishlistFormHandler('<?= $escaper->escapeHtmlAttr($wishlistFormId) ?>', '<?= $escaper->escapeUrl($url) ?>')" class="action towishlist inline-block group/wishlist p-3 lg:p-2 bg-white rounded-full shadow-sm border border-gray-100" title="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>" aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>" role="button">
                                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-5 h-5 transition-all fill-transparent duration-200 ease-in-out group-hover/wishlist:fill-primary group-hover/wishlist:stroke-primary">
                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"></path>
                                                    </svg>
                                                </button>
                                            </form>

                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <button type="button" @click.prevent="addToCompare(<?= (int)$_item->getEntityId() ?>)" class="inline-block w-max p-3 lg:p-2 group/compare bg-white rounded-full shadow-sm border border-gray-100 tocompare cursor-pointer" title="<?= $escaper->escapeHtml(__('Add to Compare')); ?>" aria-label="<?= $escaper->escapeHtml(__('Add to Compare')); ?>">
                                                    <span class="sr-only"><?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5 transition-all duration-200 ease-in-out group-hover/compare:stroke-primary">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"></path>
                                                    </svg>
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="px-4 py-3">
                                            <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                                <p class="text-sm mb-3 font-medium text-center text-black truncate block capitalize break-words">
                                                    <?= $escaper->escapeHtml($_item->getName()) ?>
                                                </p>
                                            </a>
                                            <?= $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                                            <?= $blockObj->getProductDetailsHtml($_item) ?>
                                            <?php if ($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
                                                $swatchBlock = $block->getLayout()->createBlock(\Magento\Swatches\Block\Product\Renderer\Listing\Configurable::class)->setTemplate("Magento_Swatches::product/category/renderer.phtml");
                                                /* @noEscape */
                                                echo $swatchBlock->setProduct($_item)->toHtml();

                                                $scriptBlock = $block->getLayout()->createBlock(\ViraXpress\Swatches\Block\SwatchRenderer::class)
                                                    ->setTemplate("Magento_Swatches::js/script.phtml");

                                                if ($scriptBlock->canRender()) {
                                                    echo $scriptBlock->toHtml();
                                                }
                                            } ?>
                                            <div class="flex items-end mt-3 text-xl font-semibold">
                                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                                <div class="ml-auto">
                                                    <?php
                                                    $formId = base64_encode((int)$_item->getEntityId() . "-product_list_addtocart_form");
                                                    $formId = preg_replace("/[^a-zA-Z0-9]/", "", $formId);
                                                    $url = $escaper->escapeUrl($block->getAddToCartUrl($_item, ['useUencPlaceholder' => true]));
                                                    ?>
                                                    <form id="<?= $escaper->escapeHtmlAttr($formId) ?>">
                                                        <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr((int)$_item->getEntityId()) ?>">
                                                        <button aria-label="Add to Cart" type="button" x-data="{ usedKeyboard: false }"
                                                        @keydown.window.tab="usedKeyboard = true" role="button" x-on:click="cartAddFormHandler('<?= $escaper->escapeHtmlAttr($formId) ?>', '<?= $escaper->escapeUrl($url) ?>')" title="Add to Cart" class="action tocart relative primary border-0 text-primary rounded-md" :class="{ 'focus:outline-none': !usedKeyboard }">
                                                            <svg class="h-7 w-7 text-primary" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                                                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"></path>
                                                            </svg>
                                                            <template x-if="addToCartLoader == '<?= $escaper->escapeHtmlAttr($_item->getId()) ?>'">
                                                                <span class="bg-white absolute inline-flex justify-center items-center w-full left-0 top-0 z-10 h-full">
                                                                    <svg aria-hidden="true" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-200 animate-spin fill-primary">
                                                                        <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                                                                        <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                                                                    </svg>
                                                                </span>
                                                            </template>
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php if (count($items) > 5) { ?>
                                </div>
                            <?php } else { ?>
                        </div>
                    <?php } ?>
                <?php endforeach ?>
                <?php if (count($items) > 5) { ?>
                    </div>
                </div>
            </div>
        <?php } else { ?>
    </div>
<?php } ?>
</div>

<script>
    (function() {
        const lazyImages = document.querySelectorAll("img.lazy");
        const observer = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const img = entry.target;
                    img.src = img.dataset.src;
                    img.classList.remove("lazy");

                    // Check if the next sibling element exists before removing it
                    setTimeout(() => {
                        const nextSibling = img.nextElementSibling;
                        if (nextSibling) {
                            nextSibling.remove();
                        }
                    }, 100);

                    observer.unobserve(img);
                }
            });
        });
        lazyImages.forEach(img => observer.observe(img));
    })();
</script>
<?php endif; ?>