<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php
/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter */
/** @var \Magento\LayeredNavigation\ViewModel\Layer\Filter $viewModel */
$viewModel = $block->getData('product_layer_view_model');
?>

<ol class="items space-y-2">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a
                    class="filter-navigation-url cursor-pointer flex justify-between items-center gap-2"
                    href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                    rel="nofollow"
                ><?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count w-6 h-6 inline-flex justify-center items-center rounded text-sm bg-gray-200 border border-gray-100 font-medium">
                            <?= /* @noEscape */ $localeFormatter->formatNumber((int) $filterItem->getCount()) ?></span></a>
                <?php endif; ?>
            <?php else: ?>
                <?= /* @noEscape */ $filterItem->getLabel() ?><?php
                if ($viewModel->shouldDisplayProductCountOnLayer()): ?><span
                        class="count w-6 h-6 inline-flex justify-center items-center rounded text-sm bg-gray-200 border border-gray-100 font-medium">
                            <?= /* @noEscape */ $localeFormatter->formatNumber((int) $filterItem->getCount()) ?></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>