<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var \ViraXpress\Cms\Block\Block $block */
$blockId = $block->getConfig('viraxpress_config/header/block_id');
?>

<div class="inline-block relative w-full">
    <?php if (!empty($blockId)): ?>
        <?= $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId($blockId)->toHtml(); ?>
    <?php endif; ?>
    <button class="headerPanel-closeBtn lg:hidden inline-block p-2 text-white absolute top-1/2 -translate-y-1/2 -right-4 z-10" type="button" title="Close" x-on:click="document.getElementById('header-panel').remove();">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
        </svg>
    </button>
</div>