<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php $_order = $block->getOrder() ?>
<?php $_creditmemo = $block->getCreditmemo() ?>
<?php if ($_creditmemo): ?>
    <?php $_creditmemos = [$_creditmemo]; ?>
<?php else: ?>
    <?php $_creditmemos = $_order->getCreditmemosCollection() ?>
<?php endif; ?>
<?php foreach ($_creditmemos as $_creditmemo): ?>
<div class="order-details-items creditmemo w-full">
    <div class="order-title border-b border-gray-200 py-2 px-4 text-base mb-4 flex gap-4 justify-between print:border-0 print:p-0">
        <strong><?= $escaper->escapeHtml(__('Refund #%1', $_creditmemo->getIncrementId())) ?></strong>
    </div>
    <div class="table-wrapper order-items-creditmemo w-full shadow-sm border border-gray-200 rounded-lg mb-6 p-4 bg-white print:rounded-none print:shadow-none">
        <table class="data table table-order-items creditmemo w-full" id="my-refund-table-<?= /* @noEscape */ (int) $_creditmemo->getId() ?>">
            <caption class="table-caption hidden"><?= $escaper->escapeHtml(__('Items Refunded')) ?></caption>
            <thead class="border-b border-gray-200 hidden md:table-header-group">
                <tr>
                    <th class="col name p-2 text-left text-sm font-semibold text-gray-80"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                    <th class="col price p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('Price')) ?></th>
                    <th class="col qty p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                    <th class="col subtotal p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                    <th class="col discount p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('Discount Amount')) ?></th>
                    <th class="col rowtotal p-2 text-sm font-semibold text-gray-800"><?= $escaper->escapeHtml(__('Row Total')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_creditmemo->getAllItems(); ?>
            <?php foreach ($_items as $_item): ?>
                <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
            <tfoot class="w-full block md:table-footer-group">
                <?= $block->getTotalsHtml($_creditmemo) ?>
            </tfoot>
        </table>
    </div>
    <div class="block block-order-details-view w-full shadow-sm border border-gray-200 rounded-lg mb-6 p-4 bg-white print:rounded-none print:shadow-none">
        <div class="block-title border-b border-gray-200 py-2 text-base mb-4 flex gap-4 justify-between">
            <strong><?= $escaper->escapeHtml(__('Order Information')) ?></strong>
        </div>
        <div class="block-content grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <div class="box-title">
                    <strong><?= $escaper->escapeHtml(__('Shipping Address')) ?></strong>
                </div>
                <div class="box-content">
                    <?php $_shipping = $_creditmemo->getShippingAddress() ?>
                    <address><?= /* @noEscape */ $block->formatAddress($_shipping, 'html') ?></address>
                </div>
            </div>
            <div class="box box-order-shipping-method">
                <div class="box-title">
                    <strong><?= $escaper->escapeHtml(__('Shipping Method')) ?></strong>
                </div>
                <div class="box-content">
                    <?= $escaper->escapeHtml($_order->getShippingDescription()) ?>
                </div>
            </div>
        <?php endif; ?>
            <div class="box box-order-billing-address">
                <div class="box-title">
                    <strong><?= $escaper->escapeHtml(__('Billing Address')) ?></strong>
                </div>
                <div class="box-content">
                    <?php $_billing = $_creditmemo->getbillingAddress() ?>
                    <address><?= /* @noEscape */ $block->formatAddress($_order->getBillingAddress(), 'html') ?></address>
                </div>
            </div>
            <div class="box box-order-billing-method">
                <div class="box-title">
                    <strong><?= $escaper->escapeHtml(__('Payment Method')) ?></strong>
                </div>
                <div class="box-content">
                    <?= $block->getPaymentInfoHtml() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endforeach; ?>
