<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $configHelper = $this->helper(\ViraXpress\Store\Helper\Cssconfig::class);
    $imagehelper = $this->helper(\Magento\Catalog\Helper\Image::class);
    $imageConfig = $configHelper->getConfig('viraxpress_config/image_resize/product_carousel_image_resize');
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget container block-products-list products-<?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title ">
                <h3 class="text-2xl font-bold tracking-tight text-gray-900 mb-6" role="heading" aria-level="2"><?= $escaper->escapeHtml(__($block->getTitle())) ?></h3>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="product-items <?= /* @noEscape */ $type ?> <?= /* @noEscape */ $mode ?> grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
                <?php foreach ($items as $_item): ?>
                    <div class="product-item w-full bg-white border-2 border-transparent transition duration-500 hover:rounded hover:border-2 hover:border-[#fafafa] relative group">
                        <div class="product-item-info widget-product-grid-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>">
                                <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo block rounded relative overflow-hidden flex justify-center items-center bg-[#fafafa]">
                                    <?php $productImage = $block->getImage($_item, $image);
                                    $imageWidth = ($imageConfig['width']) ? $imageConfig['width'] : $productImage->getWidth();
                                    $imageHeight = ($imageConfig['height']) ? $imageConfig['height'] : $productImage->getHeight();
                                    $productImageConfig = $imagehelper->init($_item, $image)->resize($imageWidth, $imageHeight);
                                    $productImageUrl = $productImageConfig->getUrl(); ?>
                                    <img fetchpriority="high" loading="eager" class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?> lazy transition duration-1000 ease-in-out contrast-[96%] group-hover:scale-[1.04]" id="product-image-container-list-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>" data-src="<?= $escaper->escapeUrl($productImageUrl) ?>" width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>" height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>" alt="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>" title="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>" />
                                    <span class="product photo skeleton skeleton-box absolute text-gray-400 bg-gray-100 inset-0 w-full h-full z-10 flex justify-center items-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12">
                                          <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
                                        </svg>
                                    </span>
                                </a>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="inline-flex absolute transition-all duration-500 ease-in-out top-4 right-4 flex-col gap-2 z-10">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                            <?php $wishlistParams = json_decode($block->getAddToWishlistParams($_item), true);
                                            if (isset($wishlistParams['data']) && !empty($wishlistParams['data'])) {
                                                $params['product'] = isset($wishlistParams['data']['product']) ? $wishlistParams['data']['product'] : null;
                                                $params['uenc'] = isset($wishlistParams['data']['uenc']) ? $wishlistParams['data']['uenc'] : null;
                                            }
                                            $url = isset($wishlistParams['action']) ? $wishlistParams['action'] : $block->getUrl('wishlist/index/add');
                                            $wishlistFormId = base64_encode($params['product'] . "-product_list_wishlist_form");
                                            $wishlistFormId = preg_replace("/[^a-zA-Z0-9]/", "", $wishlistFormId);
                                            ?>
                                            <form id="<?= $escaper->escapeHtmlAttr($wishlistFormId) ?>">
                                                <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($params['product']) ?>" />
                                                <input type="hidden" name="uenc" value="<?= $escaper->escapeHtmlAttr($params['uenc']) ?>" />
                                                <button type="type" role="button" x-on:click="wishlistFormHandler('<?= $escaper->escapeHtmlAttr($wishlistFormId) ?>', '<?= $escaper->escapeUrl($url) ?>')" title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>" class="action towishlist inline-block group/wishlist p-3 lg:p-2 bg-white rounded-full shadow-sm border border-gray-100">
                                                    <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-5 h-5 transition-all fill-transparent duration-200 ease-in-out group-hover/wishlist:fill-primary group-hover/wishlist:stroke-primary">
                                                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z"></path>
                                                    </svg>
                                                </button>
                                            </form>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <button type="button" x-on:click="addToCompare(<?= $escaper->escapeHtmlAttr($_item->getId()) ?>)" class="inline-block w-max p-3 lg:p-2 group/compare  bg-white rounded-full shadow-sm border border-gray-100 tocompare cursor-pointer" title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5 transition-all duration-200 ease-in-out group-hover/compare:stroke-primary">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"></path>
                                                </svg>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            <div class="product-item-details px-4 py-3">
                                <p class="mb-3 font-medium text-center text-black block capitalize">
                                    <a title="<?= $escaper->escapeHtml($_item->getName()) ?>" href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-link text-[15px]">
                                        <?= $escaper->escapeHtml($_item->getName()) ?>
                                    </a>
                                </p>
                                <?php if ($templateType): ?>
                                    <div class="text-center">
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                    </div>
                                <?php endif; ?>
                                <?php /* <?= $block->getProductDetailsHtml($_item) ?> */?>
                                <div class="flex mt-3 text-xl font-semibold items-end flex-1 w-full">
                                    <?= $block->getProductPriceHtml($_item, $type) ?>
                                    <div class="ml-auto">
                                        <?php if ($showCart): ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <?php $formId = base64_encode($postParams['data']['product'] . "-product_list_addtocart_form");
                                                $formId = preg_replace("/[^a-zA-Z0-9]/", "", $formId); ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form id="<?= $escaper->escapeHtmlAttr($formId) ?>">
                                                    <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <button aria-label="Add to Cart" role="button" type="button" x-on:click="cartAddFormHandler('<?= $escaper->escapeHtml($formId) ?>', '<?= $escaper->escapeUrl($postParams['action']) ?>')" title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>" class="action tocart relative primary border-0 text-primary rounded-md">
                                                        <svg class="h-7 w-7 text-primary" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"></path>
                                                        </svg>
                                                        <template x-if="addToCartLoader == '<?= $escaper->escapeHtml($_item->getId()) ?>'">
                                                            <span class="bg-white absolute inline-flex justify-center items-center w-full left-0 top-0 z-10 h-full">
                                                                <svg aria-hidden="true" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-200 animate-spin fill-primary">
                                                                    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                                                                    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                                                                </svg>
                                                            </span>
                                                        </template>
                                                        <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
            <?php if ($block->getPagerHtml()): ?>
                <div class="flex flex-col sm:flex-row flex-wrap justify-end items-center md:items-start gap-5 mt-5 pt-5 border-t border-gray-200">
                    <?= $block->getPagerHtml() ?>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <script>
        (function(){
            const lazyImages = document.querySelectorAll("img.lazy");
            const observer = new IntersectionObserver((entries, observer) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        const img = entry.target;
                        img.src = img.dataset.src;
                        img.classList.remove("lazy");
                        setTimeout(()=>{img.nextElementSibling.remove();}, 100)
                        observer.unobserve(img);
                    }
                });
            });
            lazyImages.forEach(img => observer.observe(img));
        })();
    </script>
<?php else: ?>
    <div class="no-product-collections-warning">
        <span><?= $escaper->escapeHtml(__("We can't find products matching the selection."))?></span>
    </div>
<?php endif; ?>
