<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>

<form class="block pb-10" x-data="Object.assign(formValidateData.formDataValidation($root,'<?= $escaper->escapeUrl($block->getFormAction()) ?>'))" @submit="onSubmit" id="contact-form">
    <div class="max-w-xl">
        <div class="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
            <div class="sm:col-span-2">
                <label class="block text-sm font-medium leading-6 text-gray-900" for="name">
                    <span><?= $escaper->escapeHtml(__('Name')) ?><span class="text-required ml-1">*</span></span>
                </label>
                <div class="mt-2.5">
                    <input name="name" id="name" title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>" value="<?= $escaper->escapeHtmlAttr($viewModel->getUserName()) ?>" type="text" required x-on:input.debounce="onChange" class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6">
                </div>
            </div>
            <div class="sm:col-span-2">
                <label class="block text-sm font-medium leading-6 text-gray-900" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?><span class="text-required ml-1">*</span></span>
                </label>
                <div class="mt-2.5">
                    <input name="email" id="email" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" value="<?= $escaper->escapeHtmlAttr($viewModel->getUserEmail()) ?>" type="email" required x-on:input.debounce="onChange" class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6">
                </div>
            </div>
            <div class="sm:col-span-2">
                <label class="block text-sm font-medium leading-6 text-gray-900" for="telephone">
                    <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
                </label>
                <div class="mt-2.5">
                    <input name="telephone" id="telephone" title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"  value="<?= $escaper->escapeHtmlAttr($viewModel->getUserTelephone()) ?>" type="tel" class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6">
                </div>
            </div>
            <div class="sm:col-span-2">
                <label class="block text-sm font-medium leading-6 text-gray-900" for="comment">
                    <span><?= $escaper->escapeHtml(__('What’s on your mind?')) ?><span class="text-required ml-1">*</span></span>
                </label>
                <div class="mt-2.5">
                    <textarea name="comment" id="comment" title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>" rows="4" class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" x-on:input.debounce="onChange" required><?= $escaper->escapeHtml($viewModel->getUserComment()) ?></textarea>
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
            <div class="mt-8 sm:col-span-2 flex justify-end">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="flex w-full justify-center items-center gap-3 transition-all rounded-md bg-primary px-3.5 py-2 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary">
                    <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </div>
</form>