<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<?php
$product = $block->getProduct();
$productId = $product->getId();
?>
<button type="button" @click.prevent="addToCompare(<?= (int)$productId ?>)" class="inline-block w-max p-3 lg:p-2 group/compare bg-white rounded-full shadow-sm border border-gray-100 tocompare cursor-pointer" title="<?= $escaper->escapeHtml(__('Add to Compare')) ?>" aria-label="<?= $escaper->escapeHtml(__('Add to Compare')) ?>" role="button">
    <span class="sr-only"><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5 transition-all duration-200 ease-in-out group-hover/compare:stroke-primary">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"></path>
    </svg>
</button>
<script>
    function initCompareOnProductList() {
        return {
            comparableProducts: [],

            init() {
                this.$watch('comparableProducts', (value) => this.$dispatch('set-compareproducts', {
                    comparableProducts: value
                }));
            },
        };
    }
</script>