<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>

<div class="p-5 bg-gray-100 rounded-lg mb-5">
    <h2 class="block text-gray-800 font-semibold mb-3">
        <?= $escaper->escapeHtml(__('Try Demo Customer Access')) ?>
    </h2>
    <p class="text-gray-800 text-sm mb-2 leading-none"><strong class="font-semibold">Email:</strong> roni_cost@example.com</p>
    <p class="text-gray-800 text-sm mb-2 leading-none"><strong class="font-semibold">Password:</strong> roni_cost3@example.com</p>
</div>