<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block \Magento\Customer\Block\Account\Forgotpassword */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget" x-data="Object.assign(formValidateData.formDataValidation($root,'<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>'))" @submit="onSubmit" id="form-validate">
    <fieldset class="fieldset space-y-6">
        <div class="field note text-sm text-gray-500"><?= $escaper->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <label for="email_address" class="label block text-sm leading-6 text-gray-900"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control mt-2">
                <input id="email" name="email" type="email" autocomplete="email" autofocus x-on:input.debounce="onChange" required class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary mt-8">
            <button type="submit" class="action submit primary primary-btn flex w-full mb-3" <?php if ($block->getButtonLockManager()->isDisabled('customer_forgot_password_form_submit')): ?> disabled="disabled" <?php endif; ?> title="<?= $escaper->escapeHtmlAttr(__('Reset My Password')) ?>">
                <span><?= $escaper->escapeHtml(__('Reset My Password')) ?></span>
            </button>
        </div>
    </div>
</form>
