<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<div class="block block-customer-login">
  <form class="form form-login" x-data="Object.assign(formValidateData.formDataValidation($root,'<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>'))" @submit="onSubmit" id="login-form" x-init="initializeLoginEmail()">
    <fieldset class="fieldset login space-y-6">
      <div class="field note text-sm text-gray-500"><?= $escaper->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
      <div class="field email">
        <label class="label block text-sm leading-6 text-gray-900" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span><span class="text-required ml-1">*</span></label>
        <div class="control mt-2">
                     <input id="email" name="login[username]" x-model="loginEmail" type="email" autofocus <?= $block->isAutocompleteDisabled() ? 'autocomplete="off"' : '' ?> value="<?= $escaper->escapeHtmlAttr($block->getUsername()) ?>" x-on:input.debounce="onChange" required class="input-text block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" />
                </div>
            </div>
            <div class="field password required">
                <label for="password" class="label block text-sm leading-6 text-gray-900"><span><?= $escaper->escapeHtml(__('Password')) ?></span><span class="text-required ml-1">*</span></label>
                <div class="control mt-2 relative">
                    <input id="password" name="login[password]" :type="showPassword ? 'text' : 'password'" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" <?= $block->isAutocompleteDisabled() ? 'autocomplete="off"' : '' ?> x-on:input.debounce="onChange" required class="input-text block w-full rounded-md border-0 pr-8 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" />
                    <div class="absolute top-1/2 right-4 z-10 cursor-pointer -translate-y-1/2">
                      <svg x-cloak x-show="showPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5" @click="showPassword = !showPassword">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>

                      <svg x-cloak x-show="!showPassword" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5" class="h-4 text-gray-700 hidden" fill="none" @click="showPassword = !showPassword">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
                      </svg>
                    </div>
                </div>
            </div>

            <?= $block->getChildHtml('form_additional_info') ?>

            <div class="actions-toolbar">
                <div class="primary mt-8">
                  <button type="submit" class="action login primary primary-btn flex w-full mb-3" <?= $block->getButtonLockManager()->isDisabled('customer_login_form_submit') ? 'disabled="disabled"' : '' ?>>
                    <template x-if="displayLoading">
                        <span class="w-6 h-6 inline-block border-2 border-white border-r-transparent rounded-full animate-spin"></span>
                    </template>
                    <span><?= $escaper->escapeHtml(__('Sign In')) ?></span>
                  </button>
                </div>
                <div class="secondary">
                  <a class="action remind font-medium text-sm text-left text-primary hover:text-primary/90" href="<?= $escaper->escapeUrl($block->getForgotPasswordUrl()) ?>">
                    <span><?= $escaper->escapeHtml(__('Forgot Your Password?')) ?></span>
                  </a>
                </div>
            </div>
        </fieldset>
    </form>
</div>
