<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\View\Element\BlockInterface $block
 * @var Escaper $escaper
 */

$formValidate = [
    'type' => 'text/javascript',
    'src' => $block->getViewFileUrl('core-js/form-validations.min.js')
];
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', $formValidate); ?>
