<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Express\Shortcut $block
 */
?>
<?php
$labelPosition = '';
if ($block->isOrPositionBefore()) {
    $labelPosition = ' before';
} elseif ($block->isOrPositionAfter()) {
    $labelPosition = ' after';
}
$shortcutHtmlId = $block->escapeHtml($block->getShortcutHtmlId());
$isInCatalogProduct = false;
if ($block->getIsInCatalogProduct()) {
    $isInCatalogProduct = $block->getIsInCatalogProduct();
}
?>

<div 
    x-data="{ checkoutUrl: '<?= $block->escapeUrl($block->getCheckoutUrl()) ?>' }"
    class="paypal checkout <?= /* @noEscape */ $labelPosition ?> paypal-logo <?= /* @noEscape */ $shortcutHtmlId ?>">
    <button 
        type="button" 
        data-action="checkout-form-submit" 
        x-on:click="window.location.href = checkoutUrl"
    >
        <img 
            src="<?= $block->escapeUrl($block->getImageUrl()) ?>" 
            alt="<?= $block->escapeHtml(__('Checkout with PayPal')) ?>" 
            class="paypal-logo"
        />
    </button>  
    <?php /* if ($block->getAdditionalLinkImage()) : ?>
        <?php $linkImage = $block->getAdditionalLinkImage(); ?>
        <a href="<?= $block->escapeUrl($linkImage['href']) ?>" class="block" title="<?= $block->escapeHtml(__('Checkout with PayPal')) ?>">
            <img src="<?= $block->escapeHtml($linkImage['src']) ?>" />
        </a>
    <?php endif; */ ?>
</div>
