<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/** @var $block \Magento\GiftMessage\Block\Cart\Item\Renderer\Actions\GiftOptions */

$gift_form = $block->getFormTemplate();
$gift_message = $block->getMessageTemplate();
$item = $block->getItem();
?>
<?php if (!$block->isVirtual()): ?>
    <div class="gift-options-cart-item w-full text-left mb-4" x-data="giftOptionsItem('<?= $escaper->escapeHtmlAttr($item->getId()) ?>')" x-cloak x-show="itemLevelMessage && isItemsLevelEnabled">
        <div class="gift-options-cart-item w-full">
            <button type="button" title="Send your message" class="inline-flex justify-start items-center gap-x-1 text-md text-primary leading-normal transition-all rounded-md bg-primary/10 p-2 text-center text-sm font-medium leading-6 focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-primary" @click="isGiftMessageOpened=!isGiftMessageOpened">
                <?= $escaper->escapeHtml(__('Gift options')) ?>
                <span class="transition-all" :class="isGiftMessageOpened == true ? 'rotate-180' :'rotate-0'">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                    </svg>
                </span>
            </button>

            <div class="my-10 space-y-5" id="gift-options-cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" x-cloak x-show="isGiftMessageOpened && isItemsLevelEnabled && isItemHasMessage">
                <div>
                    <h4 class="text-base font-semibold text-gray-900">
                        <?= $escaper->escapeHtml(__('Gift Message (optional)')) ?>
                    </h4>
                </div>
                <div class="col-span-full">
                    <label for="gift-message-whole-to-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" class="block text-sm leading-6 text-gray-900">
                        <?= $escaper->escapeHtml(__('To:')) ?>
                    </label>
                    <div class="mt-2">
                        <input type="text" name="to" id="gift-message-whole-to-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" x-model="giftItemMessage.to" autocomplete="given-name" class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" @keydown.enter.prevent>
                    </div>
                </div>
                <div class="col-span-full">
                    <label for="gift-message-whole-from-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" class="block text-sm leading-6 text-gray-900">
                        <?= $escaper->escapeHtml(__('From:')) ?>
                    </label>
                    <div class="mt-2">
                        <input type="text" id="gift-message-whole-from-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" name="from" x-model="giftItemMessage.from" autocomplete="family-name" class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6" @keydown.enter.prevent>
                    </div>
                </div>
                <div class="col-span-full">
                    <label for="gift-message-whole-message-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" class="block text-sm leading-6 text-gray-900">
                        <?= $escaper->escapeHtml(__('Message:')) ?>
                    </label>
                    <div class="mt-2">
                        <textarea name="message" id="gift-message-whole-message-<?= $escaper->escapeHtmlAttr($item->getId()) ?>" x-model="giftItemMessage.message" rows="3" class="block w-full rounded-md border-0 py-2.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6"></textarea>
                    </div>
                </div>

                <div class="col-span-full flex justify-end items-center gap-5 pt-5">
                    <button type="button" @click="giftOptionItemcancelButton($event)" data-item-id="<?= $escaper->escapeHtmlAttr($item->getId()) ?>" class="inline-block text-sm leading-6 text-gray-900">
                        <?= $escaper->escapeHtml(__('Cancel')) ?>
                    </button>
                    <button type="button" x-on:click="giftOptionsItemFormSubmit($event)" class="inline-flex justify-center items-center gap-3 transition-all rounded-md bg-primary px-3 py-1.5 text-sm  leading-6 text-white shadow-sm hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary">
                        <span><?= $escaper->escapeHtml(__('Update')) ?></span>
                        <span id="form-spinner" role="status" x-show="addSpinner">
                            <svg aria-hidden="true" class="w-5 h-5 mr-2 text-gray-400 animate-spin fill-white" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"></path>
                                <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"></path>
                            </svg>
                            <span class="sr-only"><?= $escaper->escapeHtml(__('Loading...')) ?></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="gift-summary bg-neutral-50 p-3 border border-neutral-100 rounded mt-4 flex justify-between items-start gap-5" x-cloak x-show="isGiftMessageOpened && !isItemHasMessage">
                <div class="gift-message-summary text-md font-regular">
                    <span class="font-medium block w-full mb-2"><?= $escaper->escapeHtml(__('Message:')) ?></span>
                    <span x-text="giftItemMessage.message"></span>
                </div>
                <div class="actions-toolbar">
                    <div class="secondary">
                        <button type="button" x-on:click="editGiftOptionItemMessage" class="action-edit text-green-600 inline-block cursor-pointer p-2 rounded-full hover:bg-green-100" title="Edit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                            </svg>
                        </button>
                        <button class="action-remove text-red-600 inline-block cursor-pointer p-2 rounded-full hover:bg-red-100" x-on:click="deleteItemGiftMessage" title="Delete">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" viewBox="0 0 24 24" width="22" height="22" aria-hidden="true">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m19 7-.867 12.142A2 2 0 0 1 16.138 21H7.862a2 2 0 0 1-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v3M4 7h16"></path>
                                </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>