<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Text */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>

<div class="mt-5 field<?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA) {
    echo ' textarea';
                      } ?><?= /* @noEscape */ $class ?>">
    <label class="label inline-block text-sm font-medium text-gray-900" for="options_<?= $escaper->escapeHtmlAttr($_option->getId()) ?>_text">
        <span>
            <?= $escaper->escapeHtml($_option->getTitle()) ?>
            (<?= /* @noEscape */ $block->getFormattedPrice() ?>)
        </span>
        <?php if ($_option->getIsRequire()): ?>
            <span class="text-required ml-1">*</span>
        <?php endif; ?>
    </label>
    <div class="control mt-2">
        <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_FIELD): ?>
            <?php $_textValidate = null;
            if ($_option->getIsRequire()) {
                $_textValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textValidate['maxlength'] = $_option->getMaxCharacters();
            }
            $_textValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <input type="text"
                   id="options_<?= $escaper->escapeHtmlAttr($_option->getId()) ?>_text"
                   class="input-text product-custom-option"
                   hx-on:change="changeCustomizableOption(event)" <?= /* @noEscape */ $class ?>
                <?php if (!empty($_textValidate)) {?>
                    data-validate="<?= $escaper->escapeHtml(json_encode($_textValidate)) ?>"
                <?php } ?>
                   name="options[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                   data-selector="options[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $escaper->escapeHtml($block->getDefaultValue()) ?>"/>
        <?php elseif ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA): ?>
            <?php $_textAreaValidate = null;
            if ($_option->getIsRequire()) {
                $_textAreaValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textAreaValidate['maxlength'] = $_option->getMaxCharacters();
            }
            $_textAreaValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <textarea id="options_<?= $escaper->escapeHtmlAttr($_option->getId()) ?>_text"
                      class="product-custom-option" <?= /* @noEscape */ $class ?>
                      hx-on:change="changeCustomizableOption(event)"
                    <?php if (!empty($_textAreaValidate)) {?>
                        data-validate="<?= $escaper->escapeHtml(json_encode($_textAreaValidate)) ?>"
                    <?php } ?>
                      name="options[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                      data-selector="options[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                      rows="5"
                      cols="25"><?= $escaper->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
        <?php if ($_option->getMaxCharacters()): ?>
            <p class="note note_<?= $escaper->escapeHtmlAttr($_option->getId()) ?>">
                <?= $escaper->escapeHtml(__('Maximum %1 characters', $_option->getMaxCharacters())) ?>
                <span class="character-counter no-display"></span>
            </p>
        <?php endif; ?>
    </div>
    <?php if ($_option->getMaxCharacters()):?>
        <!-- removed js script. please refer the default template file for reference -->
    <?php endif; ?>
</div>
