<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/**
 * @var $block \Magento\Tax\Block\Checkout\Shipping
 * @see \Magento\Tax\Block\Checkout\Shipping
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->displayShipping()): ?>
    <?php
        $style = $escaper->escapeHtmlAttr($block->getStyle());
        $colspan = (int) $block->getColspan();
        /** @var \Magento\Checkout\Helper\Data $checkoutHelper */
        $checkoutHelper = $block->getData('checkoutHelper');
    ?>
    <?php if ($block->displayBoth()): ?>
    <tr class="totals shipping excl">
        <th class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
            <?= $escaper->escapeHtml($block->getExcludeTaxLabel()) ?>
        </th>

        <td class="amount" data-th="<?= $escaper->escapeHtmlAttr($block->getExcludeTaxLabel()) ?>">
            <?= /* @noEscape */ $checkoutHelper->formatPrice($block->getShippingExcludeTax()) ?>
        </td>
    </tr>
        <?php if ($style): ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.excl th.mark') ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.excl td.amount') ?>
        <?php endif; ?>
    <tr class="totals shipping incl">
        <th class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
            <?= $escaper->escapeHtml($block->getIncludeTaxLabel()) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtmlAttr($block->getIncludeTaxLabel()) ?>">
            <?= /* @noEscape */ $checkoutHelper->formatPrice($block->getShippingIncludeTax()) ?>
        </td>
    </tr>
        <?php if ($style): ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.incl th.mark') ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.incl td.amount') ?>
        <?php endif; ?>
    <?php elseif ($block->displayIncludeTax()): ?>
    <tr class="totals shipping incl">
        <th class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
            <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtmlAttr($block->getTotal()->getTitle()) ?>">
            <?= /* @noEscape */ $checkoutHelper->formatPrice($block->getShippingIncludeTax()) ?>
        </td>
    </tr>
        <?php if ($style): ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.incl th.mark') ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.incl td.amount') ?>
        <?php endif; ?>
    <?php else: ?>
    <tr class="totals shipping excl">
        <th class="mark" colspan="<?= /* @noEscape */ $colspan ?>" scope="row">
            <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtmlAttr($block->getTotal()->getTitle()) ?>">
            <?= /* @noEscape */ $checkoutHelper->formatPrice($block->getShippingExcludeTax()) ?>
        </td>
    </tr>
        <?php if ($style): ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.excl th.mark') ?>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($style, 'tr.totals.shipping.excl td.amount') ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
