<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/**
 * @var $block \Magento\Tax\Block\Checkout\Tax
 * @see \Magento\Tax\Block\Checkout\Tax
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
    $_value = $block->getTotal()->getValue();
    $_style = $escaper->escapeHtmlAttr($block->getTotal()->getStyle());
    /** @var \Magento\Tax\Helper\Data $taxHelper */
    $taxHelper = $block->getData('taxHelper');
    /** @var \Magento\Checkout\Helper\Data $checkoutHelper */
    $checkoutHelper = $block->getData('checkoutHelper');
    $attributes = 'class="totals-tax"';

if ($taxHelper->displayFullSummary() && $_value != 0) {
    $attributes = 'class="totals-tax-summary" data-mage-init=\'{"toggleAdvanced": {"selectorsToggleClass": "shown",
     "baseToggleClass": "expanded", "toggleContainers": ".totals-tax-details"}}\'';
}
?>

<tr <?= /* @noEscape */ $attributes ?>>
    <th class="mark" colspan="<?= (int) $block->getColspan() ?>" scope="row">
        <?php if ($taxHelper->displayFullSummary()): ?>
            <span class="detailed"><?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?></span>
        <?php else: ?>
            <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        <?php endif; ?>
    </th>
    <td class="amount" data-th="<?= $escaper->escapeHtmlAttr($block->getTotal()->getTitle()) ?>">
        <?= /* @noEscape */ $checkoutHelper->formatPrice($_value) ?>
    </td>
</tr>
<?php if ($_style): ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax th.mark') ?>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax td.amount') ?>
<?php endif; ?>

<?php if ($taxHelper->displayFullSummary() && $_value != 0): ?>
    <?php foreach ($block->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) { continue; } ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
            <tr class="totals-tax-details">
                <th class="mark" colspan="<?= (int) $block->getColspan() ?>" scope="row">
                    <?= $escaper->escapeHtml($rate['title']) ?>
                    <?php if ($rate['percent'] !== null): ?>
                        (<?= (float) $rate['percent'] ?>%)
                    <?php endif; ?>
                </th>
                <?php if ($isFirst): ?>
                    <td class="amount" rowspan="<?= count($rates) ?>"
                       data-th="<?= $escaper->escapeHtmlAttr($rate['title']) ?>
                        <?php if ($rate['percent'] !== null): ?>(<?= (float) $rate['percent'] ?>%)<?php endif; ?>">
                        <?= /* @noEscape */ $checkoutHelper->formatPrice($amount) ?>
                    </td>
                <?php endif; ?>
            </tr>
            <?php if ($_style): ?>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax-details th.mark') ?>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag($_style, 'tr.totals-tax-details td.amount') ?>
            <?php endif; ?>
            <?php $isFirst = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>
