<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
$schema = ($block->getZone() == 'item_view') ? true : false;
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
$configuredPrice = $block->getPrice();
/** @var \Magento\Catalog\Pricing\Price\ConfiguredRegularPrice $configuredRegularPrice */
$configuredRegularPrice = $block->getPriceType(
    \Magento\Catalog\Pricing\Price\ConfiguredPriceInterface::CONFIGURED_REGULAR_PRICE_CODE
);
?>
<?php if ($configuredPrice->getAmount()->getValue() < $configuredRegularPrice->getAmount()->getValue()): ?>
    <p class="price-as-configured">
        <span class="special-price">
            <?= /* @noEscape */ $block->renderAmount(
                $configuredPrice->getAmount(),
                [
                    'display_label'     => $escaper->escapeHtml(__('Special Price')),
                    'price_id'          => $escaper->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema,
                ]
            ); ?>
        </span>
        <span class="old-price">
            <?= /* @noEscape */ $block->renderAmount(
                $configuredRegularPrice->getAmount(),
                [
                    'display_label'     => $escaper->escapeHtml(__('Regular Price')),
                    'price_id'          => $escaper->escapeHtml($block->getPriceId('old-price-' . $idSuffix)),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true,
                ]
            ); ?>
        </span>
    </p>
<?php else: ?>
    <?php
    $priceLabel = ($block->getPriceLabel() !== null)
        ? $block->getPriceLabel()
        : '';
    ?>
    <p class="price-as-configured">
        <?= /* @noEscape */ $block->renderAmount(
            $configuredPrice->getAmount(),
            [
                'display_label'     => $escaper->escapeHtml($priceLabel),
                'price_id'          => $escaper->escapeHtml($block->getPriceId('product-price-' . $idSuffix)),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema,
            ]
        ); ?>
    </p>
<?php endif; ?>
